### ISSUE TITLE
Feature gate dependencies

### ISSUE THREAD

**Issue by ritchie46** [sfu-db/connector-x#102]
With the new arrow support, I think connector-x has value as a rust crate as well. However, as a crate owner writing a library, I'd not want to depend on connector-x because it has a lot of dependencies (increasing compile times), I'd don't want to compile.

I think it would be really valuable if the dependencies could be opt-in and activated with feature gates.

**Comment by dovahcrow** [comment]
Yes, correct! I'm also considering releasing the rust crate after the 0.2.0 python version is released. There are more than dependency problems on the Rust crate before we can release it (e.g. documentation). 

Luckily I think the release of the Rust crate can be decoupled with the python version.

**Comment by dovahcrow** [comment]
@ritchie46 Now I moved all the {sources, destinations} under their own feature gates. Most of the dependencies are now optional. Does it look good to you?
https://github.com/sfu-db/connector-x/blob/ad47e84e65b1c8f0a98f8e5e5bbccb12e308c370/connectorx/Cargo.toml.

**Comment by ritchie46** [comment]
> If you don't specify any feature, the dependencies required are reduced from 338 to 47.

That's a great improvement. :) Congrats on the release.

Do you think that a future release on stable may be possible, perhaps behind a feature gate as well? For binaries, nightly isn't a problem, but I can imagine that libraries are reluctant depending on nightly features.

**Comment by dovahcrow** [comment]
> > If you don't specify any feature, the dependencies required are reduced from 338 to 47.
> 
> That's a great improvement. :) Congrats on the release.
> 
> Do you think that a future release on stable may be possible, perhaps behind a feature gate as well? For binaries, nightly isn't a problem, but I can imagine that libraries are reluctant depending on nightly features.

We use the GAT feature in the core part of the code so I guess it is not easy to move it to a feature gate. The best case is GAT becoming stabilized in October (https://github.com/rust-lang/rust/issues/44265#issuecomment-869888398).
