### ISSUE TITLE
Postgres SSL Support

### ISSUE THREAD

**Issue by wseaton** [sfu-db/connector-x#103]
Currently no TLS implementation is supported, so connecting like this fails if the DB mandates an SSL/TLS connection:

`df = cx.read_sql(f"postgresql://{username}:{password}@host:35432/schema?sslmode=require", 'select 1;', return_type='pandas')`

Error:
```
RuntimeError: timed out waiting for connection: error performing TLS handshake: no TLS implementation configured
```

Is this a planned feature? It seems to be supported upstream in `rust-postgres`: https://docs.rs/postgres-native-tls/0.5.0/postgres_native_tls/

The lack of SSL support (even with `sslmode=require`) makes it difficult to use connector-x in enterprise-y environments.

**Comment by dovahcrow** [comment]
Thanks for the reminder on SSL! I almost forgot this important feature. Will add this to the todo list for v0.2.0
