### ISSUE TITLE
Rust Arrow2 Support

### ISSUE THREAD

**Issue by wseaton** [sfu-db/connector-x#113]
It would be awesome if the rust crate could depend on the `arrow2` branch of polars upstream since that is now where pypolars python releases are coming from. Happy to help test this if necessary. 

https://github.com/pola-rs/polars/tree/arrow2

**Comment by jorgecarleitao** [comment]
I can take a shot at this (thanks @ritchie46 for the ping)

**Comment by dovahcrow** [comment]
@jorgecarleitao @ritchie46 Thanks for the help in advance!
