### ISSUE TITLE
not implemented: MYSQL_TYPE_TINY

### ISSUE THREAD

**Issue by patcollis34** [sfu-db/connector-x#115]
this error is return when trying to read a mysql table that contains a tiny int: '<unnamed>' panicked at 'not implemented: MYSQL_TYPE_TINY', connectorx/src/sources/mysql/typesystem.rs:44:18

**Comment by dovahcrow** [comment]
Hi @patcollis34 the support of tiny int is added in this commit https://github.com/sfu-db/connector-x/commit/5e24dfb6bcfe172028a4eff488a01543cdf4d807#diff-457a3807bb769afd777a94d238703648d0c358e8703e1877a84eb1af0fda13d1 but hasn't been released. We will have a new release soon.

**Comment by wangxiaoying** [comment]
Hi @patcollis34 , we just released the connectorx-0.2.1a1 which has included the tinyint type. You can try it by using pip install -U connectorx==0.2.1a1.

If all tests go well, we plan to release the 0.2.1 version in early October. Please feel free to have a try and let us know if you found any issue.

**Comment by patcollis34** [comment]
That's awesome thanks for the quick turnaround!
