### ISSUE TITLE
Not able to install connectorx library in MacOS

### ISSUE THREAD

**Issue by open1312** [sfu-db/connector-x#119]
After creating the virtual environment in my MacOS when I try to do `pip install connectorx` it is saying

`Error: Could not find a version that satisfies the requirement connectorx (from versions : none)`

**Comment by wangxiaoying** [comment]
@open1312 Which python version are you using? connectorx support python >= 3.7

**Comment by dovahcrow** [comment]
Hi @open1312, are you using the M1 version of mac?

**Comment by open1312** [comment]
@dovahcrow - Yes, I am using M1 version of Mac OS. But no worries the issue got solved I have installed the package in conda environment

**Comment by dovahcrow** [comment]
@open1312 I think we currently don't provide the M1 version of ConnectorX. May I ask if your Conda environment is intel-based?
