### ISSUE TITLE
Operators for pattern matching using POSIX regular expressions gives sql parser error

### ISSUE THREAD

**Issue by ds-noahdolev** [sfu-db/connector-x#120]
Hi,

I am testing out connectorX for a postgres query but I run into some trouble with operators in my query. 

```{SQL}
SELECT 
 CASE
     WHEN something ~* '.*somestring.*' THEN 'someotherstring'
 END as someposix
FROM MY_DB
```

Gives:
`RuntimeError: sql parser error: Expected THEN, found: ~`

This query runs fine using SQLAlchemy+Pandas. Any ideas?

**Comment by wangxiaoying** [comment]
@ds-noahdolev thanks for the report! It seems like the underlying sqlparser crate we use is an old version and does not support posix regex. We have updated it to the newest version and make it into our newest alpha release. You can try it by using `pip install -U connectorx==0.2.1a2`. Please let us know if you found any issue.

**Comment by ds-noahdolev** [comment]
Works! Thanks so much!
