### ISSUE TITLE
Add Benchmark against turbodbc

### ISSUE THREAD

**Issue by DD5HT** [sfu-db/connector-x#124]
It would be nice to see a benchmark against turbodbc since it was often proclaimed to be the fastest way of fetching data to pandas.

https://github.com/blue-yonder/turbodbc

**Comment by wangxiaoying** [comment]
Hi @DD5HT , we just added the benchmark against `turbodbc`. You can find the result [here](https://github.com/sfu-db/connector-x/blob/main/Benchmark.md#benchmark-result-on-aws-r54xlarge).
