### ISSUE TITLE
how to connect to for MSSQL

### ISSUE THREAD

**Issue by Arengard** [sfu-db/connector-x#140]

**Comment by Arengard** [comment]
Hi i am stuck 


username ='user'
password = 'pasword'
host = 'MSSQL\SQL2019'
db= 'db'
port=1433
c = f'mssql://{username}:{password}@{host}:{port}/{db}'
q ='select * from user'

cx.read_sql(conn=c, query=q, return_type='polars')

############################## RuntimeError #############################

----> 9 cx.read_sql(conn=c, query=q, return_type='polars')

~\AppData\Local\Programs\Python\Python37\lib\site-packages\connectorx\__init__.py in read_sql(conn, query, return_type, protocol, partition_on, partition_range, partition_num)
    131             queries=queries,
    132             protocol=protocol,
--> 133             partition_query=partition_query,
    134         )
    135         df = reconstruct_arrow(result)

RuntimeError: parse error: invalid domain character

############################## RuntimeError #############################

**Comment by Arengard** [comment]
########################## PanicException: not implemented: Money ######################

\AppData\Local\Programs\Python\Python37\lib\site-packages\polars\io.py in read_sql(sql, connection_uri, partition_on, partition_range, partition_num)
    640             partition_on=partition_on,
    641             partition_range=partition_range,
--> 642             partition_num=partition_num,
    643         )
    644         return pl.from_arrow(tbl)  # type: ignore[return-value]

~\AppData\Local\Programs\Python\Python37\lib\site-packages\connectorx\__init__.py in read_sql(conn, query, return_type, protocol, partition_on, partition_range, partition_num)
    131             queries=queries,
    132             protocol=protocol,
--> 133             partition_query=partition_query,
    134         )
    135         df = reconstruct_arrow(result)

########################## PanicException: not implemented: Money ######################

**Comment by siklosg** [comment]
I'm having trouble connecting to MS SQL Server as well. My problem is not with the password however, but the server and instance definition. For SQL Server, you can specify an instance like myserver\myinstance. The connection string parser seems to have trouble with this and I get a `RuntimeError: parse error: invalid domain character`. The whole connection string looks like this: `'mssql://user:password@myserver\myinstance:1433/mydatabase`

**Comment by bloukanov** [comment]
@siklosg I actually had the same issue, and so instead of `myserver\myinstance:1433`, I ended up doing `myserver:portnumber`, so my connection string is `mssql://user:password@myserver:portnumber/mydatabase`

I am not sure if every instance has a unique port number, but this worked in my case. I asked IT for the port number.

**Comment by wangxiaoying** [comment]
> I'm having trouble connecting to MS SQL Server as well. My problem is not with the password however, but the server and instance definition. For SQL Server, you can specify an instance like myserver\myinstance. The connection string parser seems to have trouble with this and I get a `RuntimeError: parse error: invalid domain character`. The whole connection string looks like this: `mssql://user:password@myserver\myinstance:1433/mydatabase`

Hi @siklosg, thanks for the report. I didn't know mssql has `host\instance` access before. I've added this support in the new alpha version `0.2.2-alpha.3`, the pipeline is still running [here](https://github.com/sfu-db/connector-x/actions/runs/1424639275) and should be available when it is finished. However, since I'm using `mssql` docker for test it does not support instance name, so I cannot test it locally. Can you check whether it works? The connection url is: `mssql://user:password@myserver%5Cmyinstance:port/mydatabase`.

The workaround mentioned by @bloukanov above also works since the instance name will be replaced with the port number eventually. It can be a quick fix if the new alpha version still have issue.

**Comment by bloukanov** [comment]
hi @wangxiaoying, I am getting an error when I try to download to `polars`:

`AttributeError: type object 'DataFrame' has no attribute 'from_arrow'`

I wonder if it is because of the version I am using (`0.2.1-alpha.6`)? I updated polars to `0.10.8` and still same issue. Should I downgrade polars?

Any help is greatly appreciated!

full traceback:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
c:\Users\loukanob\Documents\pydev-profiling\feature_mart\test_connector_x.py in <module>
     20     ,return_type='polars'
     21     ,partition_on = 'partition'
---> 22     ,partition_num=4
     23     )
     24 

~\Anaconda3\lib\site-packages\connectorx\__init__.py in read_sql(conn, query, return_type, protocol, partition_on, partition_range, partition_num)
    140                 raise ValueError("You need to install polars first")
    141 
--> 142             df = pl.DataFrame.from_arrow(df)
    143     else:
    144         raise ValueError(return_type)

AttributeError: type object 'DataFrame' has no attribute 'from_arrow'
```

**Comment by wangxiaoying** [comment]
> hi @wangxiaoying, I am getting an error when I try to download to `polars`:
> 
> `AttributeError: type object 'DataFrame' has no attribute 'from_arrow'`
> 
> I wonder if it is because of the version I am using (`0.2.1-alpha.6`)? I updated polars to `0.10.8` and still same issue. Should I downgrade polars?
> 
> Any help is greatly appreciated!
> 
> full traceback:
> 
> ```
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> c:\Users\loukanob\Documents\pydev-profiling\feature_mart\test_connector_x.py in <module>
>      20     ,return_type='polars'
>      21     ,partition_on = 'partition'
> ---> 22     ,partition_num=4
>      23     )
>      24 
> 
> ~\Anaconda3\lib\site-packages\connectorx\__init__.py in read_sql(conn, query, return_type, protocol, partition_on, partition_range, partition_num)
>     140                 raise ValueError("You need to install polars first")
>     141 
> --> 142             df = pl.DataFrame.from_arrow(df)
>     143     else:
>     144         raise ValueError(return_type)
> 
> AttributeError: type object 'DataFrame' has no attribute 'from_arrow'
> ```

Hi @bloukanov , can you upgrade to the newest alpha version: `0.2.2-alpha.3` and try again? I think this issue has been fixed in this PR: https://github.com/sfu-db/connector-x/pull/154

**Comment by bloukanov** [comment]
@wangxiaoying amazing thanks!! works

**Comment by pd2871** [comment]
The TCP/IP needs to be enabled before trying to connect to mssql. If it is disabled by default, it wont work.

To enable TCP/IP, its needs to be followed this way:

1. Open run shell (window+R) and Run this command using 
```
SQLServerManager15.msc
```

2. The command might change based on SQL Server version. Can be selected from [here](https://learn.microsoft.com/en-us/sql/relational-databases/sql-server-configuration-manager?view=sql-server-ver16#:~:text=the%20C%20drive.-,Version,Path,-SQL%20Server%202022)

3. Click on `SQL Server Network Configuration` followed by `Protocols for MSQLSERVER`

4. Right click on TCP/IP and enable it.

5. You can also find the port number which is by default `1433` by right clicking on TCP/IP and clicking Properties and clicking the IP Addresses.

6. MSSQL also needs to be restarted so Click “OK” on the Warning that the service will have to be restarted

7. Click on “SQL Server Services”

8. Right click on “SQL Server (MSSQLSERVER) and choose “Restart”

The command to run MSSQL:

```
mssql://user:password@myserver:portnumber/mydatabase?trusted_connection=true&encrypt=true
```

Eg.
```
import connectorx as cx

SQL_DATABASE_URI = "mssql://admin:12345@mssqlproject.database.windows.net:1433/db1?trusted_connection=true&encrypt=true"
df = cx.read_sql(SQL_DATABASE_URI, f"Select * from table1")
```

If the password is complex:
```
import connectorx as cx
from urllib import parse

SQL_DATABASE_URI  = "mssql://admin:%s@mssqlproject.database.windows.net:1433/db1?trusted_connection=true&encrypt=true" % parse.quote_plus("12345@!!")
df = cx.read_sql(SQL_DATABASE_URI, f"Select * from table1")
```

**Comment by evbo** [comment]
@wangxiaoying could we possibly reopen this? I'm wondering if complex passwords/users might still be incompatible?

If I use pymssql, I can connect just fine (so I know this user works):
```python
import pymssql
conn = pymssql.connect("fehchdev.com", "FEHCH\oper_dev", "b3k@!!1aa", "registrar_home")
cursor = conn.cursor(as_dict=True)
cursor.execute("select * from dbs1.users_home")
row = cursor.fetchone()
print(row)
```

If I use connectorx, I get the same error as in above comments (timeout in bb8):

```python
from urllib import parse
import connectorx as cx

u = parse.quote_plus("FEHCH\oper_dev")
p = parse.quote_plus("b3k@!!1aa")
host = "fehchdev.com"
db = "registrar_home"
uri = f"mssql://{u}:{p}@{host}:1433/{db}"

cx.read_sql(uri, "select * from dbs1.users_home")
```

> RuntimeError('Timed out in bb8')

I've tried several combinations too, the only difference is `encrypt=true` takes longer to log any errors:

```python
uri = f"mssql://{u}:{p}@{host}:1433/{db}?trusted_connection=true&encrypt=true"
uri = f"mssql://{u}:{p}@{host}:1433/{db}?trusted_connection=true&encrypt=false"
uri = f"mssql://{u}:{p}@{host}:1433/{db}?trusted_connection=false&encrypt=false"
uri = f"mssql://{u}:{p}@{host}:1433/{db}?driver=SQL+Server&trusted_connection=true&encrypt=true"

```

**Comment by SantiScandorla** [comment]
I have several problems with the connection between Python and Microsoft SQL Server Management Studio. I need to use connectorx since I would like to use polars dataframe. I attach the code and the error: 

`import connectorx as cx 
import urllib.parse

conn = 'mssql://MYUSER:{}@{}:1433/MYDATABASE?encrypt=true&trusted_connection=true'.format(
    urllib.parse.quote_plus('MYPASSWORD'),
    urllib.parse.quote_plus('MYSERVER')
    )                                                                        
str_query = f"SELECT * FROM raw.calendar"

cx.read_sql(conn,str_query)`

> RuntimeError: Timed out in bb8

**Comment by jmpalumbo** [comment]
Hello, I am opening this thread back up again. I cannot connect to a MsSQL DB using Connector X. However, I can successfully connect using PyODBC -> pl.raed_database. 

When I attempt to connect using the following syntax with `parse.quote_plus()`  and `cx.read_sql(URI, Query)`, `mssql://username:password@server:port/database?encrypt=true&trusted_connection=true`, I receive the following ValueError in association with the timed out in bb8 error: `"You need to install pandas first"`

If I do the same using Polars pl.read_database, I receive ValueError `"You need to install pyarrow first"` with the timed out in bb8 error.

I have both pandas (2.1.4) and pyarrow (14.0.2) installed in my venv with Python version 3.10.13 and Connector X version 0.3.2. 

I want to use Connector X if possible. Thank you for any help.

**Comment by leonkosak** [comment]
> Hello, I am opening this thread back up again. I cannot connect to a MsSQL DB using Connector X. However, I can successfully connect using PyODBC -> Polars pl.read_database. 
> 
> When I attempt to connect using the following syntax with `parse.quote_plus()`  and `cx.read_sql(URI, Query)`, `mssql://username:password@server:port/database?encrypt=true&trusted_connection=true`, I receive the following ValueError in association with the timed out in bb8 error: `"You need to install pandas first"`
> 
> If I do the same using Polars pl.read_database_uri, I receive ValueError `"You need to install pyarrow first"` with the timed out in bb8 error.
> 
> I have both pandas (2.1.4) and pyarrow (14.0.2) installed in my venv with Python version 3.10.13 and Connector X version 0.3.2. 
> 
> I want to use Connector X if possible. Thank you for any help.
> 
> 
> 

I have exactly the same issue.
I would really like to use Polars and ConnectorX to get some additional processing speed.
Thank you for help.

**Comment by kuro337** [comment]
Does anyone know how we can use Polars if I open a connection with pyodbc?

ConnectX and Polars does not seem to work at all under any variation , interested to see if there is any workaround/solution
