### ISSUE TITLE
Mssql Money type not supported

### ISSUE THREAD

**Issue by Arengard** [sfu-db/connector-x#141]
########################## PanicException: not implemented: Money ######################

**Comment by wangxiaoying** [comment]
Money type has been added to v0.2.2.

**Comment by jtlz2** [comment]
Why do I get 

`PanicException: not implemented: money
`
when running a simple query from 0.2.5?

**Comment by wangxiaoying** [comment]
> Why do I get
> 
> `PanicException: not implemented: money`
> 
> when running a simple query from 0.2.5?

@jtlz2 That's weird, we have the [type money test](https://github.com/sfu-db/connector-x/blob/main/connectorx-python/connectorx/tests/test_mssql.py#L447) and it passes in our ci. Can you make sure you are using the latest version of connectorx? If that's still the error, can you provide an example (queries for table creation and insert example data into it) so we can reproduce the error?
