### ISSUE TITLE
mssql uniqueidentifiers downloaded in lower case

### ISSUE THREAD

**Issue by bloukanov** [sfu-db/connector-x#151]
Hi,

I find that uniqueidentifier fields are being downloaded in lower case from MS SQL - do you see the same issue?

**Comment by wangxiaoying** [comment]
Hi @bloukanov ,

Seems like mssql stores uniqeidentifier in 16-byte GUID, which is a number and will be represented as a string of hexadecimal digit. I tried using both `mssql-cli` client and `pymssql` driver, they all show the lowercase result.
![image](https://user-images.githubusercontent.com/5569610/139960818-5609ee12-0bf0-4c20-ac72-4656b93fa988.png)

If you want to get an uppercase result, one way is to convert the type into a string, for example:
```sql
select CONVERT(VARCHAR(50), test_uuid) as test_uuid from table
```
It will return the uppercase result

**Comment by bloukanov** [comment]
thanks @wangxiaoying it is actually easy enough for me to do `df.id.str.upper()` after the download. just wanted to bring it up! pd.read_sql downloads it in upper case

**Comment by wangxiaoying** [comment]
> thanks @wangxiaoying it is actually easy enough for me to do `df.id.str.upper()` after the download. just wanted to bring it up! pd.read_sql downloads it in upper case

I think it depends on the underlying driver. In my case through `pd.read_sql`, using `pymssql` engine (https://docs.sqlalchemy.org/en/14/core/engines.html#microsoft-sql-server) the result is in lower case.

Actually we do not produce this string by ourselves but only get the value from the underlying Rust driver (https://docs.rs/tiberius/0.6.5/tiberius/). Seems like there is no regulation on this case ([C# in lowercase](https://stackoverflow.com/questions/16938151/uniqueidentifier-in-sql-becomes-lower-case-in-c-sharp) and [JDBC in uppercase](https://stackoverflow.com/questions/62833001/uniqueidentifier-issue-with-casesensitive-in-sqlserver)), so I will close this issue for now. But thanks for bringing it up anyway!

**Comment by bloukanov** [comment]
@wangxiaoying  ah I see, got it!
