### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement connectorx (from versions: none)

### ISSUE THREAD

**Issue by Arengard** [sfu-db/connector-x#157]
on python 3.10.0

this -> pip install connectorx ->runs into

ERROR: Could not find a version that satisfies the requirement connectorx (from versions: none)
ERROR: No matching distribution found for connectorx

**Comment by aehsaei** [comment]
same issue (on python 3.7)

**Comment by wseaton** [comment]
> on python 3.10.0

@Arengard there are currently no wheels available on [pypi for any version above 3.9](https://pypi.org/project/connectorx/0.2.2a1/#files), also no wheels currently being built for M1 compatible macs.

**Comment by wangxiaoying** [comment]
> on python 3.10.0
> 
> this -> pip install connectorx ->runs into
> 
> ERROR: Could not find a version that satisfies the requirement connectorx (from versions: none) ERROR: No matching distribution found for connectorx

Hi @Arengard , wheels for python 3.10 are ready! You can try it by using `pip install -U connectorx==0.2.2a2`. Please let us know if you found any issue.
