### ISSUE TITLE
Support unsigned in MySQL

### ISSUE THREAD

**Issue by fearcon-eap** [sfu-db/connector-x#163]
I get this PanicException in python
```
PanicException: Could not retrieve core::option::Option<i8> from Value

thread '<unnamed>' panicked at 'Could not retrieve core::option::Option<i8> from Value', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\mysql_common-0.27.5\src\value\convert\mod.rs:175:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

when running the following query against the a table with the generalized structure as given below.
`SELECT Var1,VarX FROM Table WHERE SOME FILTER on Var1`

The exception occurs for X=2 but not X=3.
There are more variables that are unsigned tinyint(3) with max value 255 in the table and they seem to all produce the same problem.
The same query works without problems for X=3 and variables of other types.

I don't have more data available for testing right now, but I would guess that the problem occurs as soon as a value in the result is larger than 127 (the maxium value for a (signed) tinyint in MYSQL) [Integer Types in MYSQL](https://dev.mysql.com/doc/refman/8.0/en/integer-types.html).

sql_url = "mysql://user:pass@server/dbname"

**Table Structure**

| Name | Type | Attributes | NULL | Default | Max value in filtered result
| ----------- | ----------- | ----------- | ----------- | ----------- | ----------- |
|       Var1    |  datetime(4) |               | YES           | NULL     |
|       Var2    | tinyint(3)      | UNSIGNED     | YES   | NULL    | 255
|       Var3    | tinyint(3)      | UNSIGNED     | YES   | NULL    | 1

```
cx.version('connectorx')
'0.2.1'
sys.version
'3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]'
```

I would have liked to investigate the backtrace, or to attach the backtrace, but I unfortunately don't understand how to activate it.
I tried 
`os.environ['RUST_BACKTRACE']='1'`
but that did not change anything.

**Comment by wangxiaoying** [comment]
Hi @fearcon-eap , thanks for reporting this issue. The reason for this is because we are currently not checking the unsigned flag for numerical values, so we will treat all of the integers as signed. We will fix it in our next release (Nov 23rd). Please let me know if you need it earlier, then I can release an alpha version for you first.

**Comment by fearcon-eap** [comment]
> Hi @fearcon-eap , thanks for reporting this issue. The reason for this is because we are currently not checking the unsigned flag for numerical values, so we will treat all of the integers as signed. We will fix it in our next release (Nov 23rd). Please let me know if you need it earlier, then I can release an alpha version for you first.

This is great news, thank you!
I can wait one week, and use that week to add more data to the table :p

**Comment by wangxiaoying** [comment]
The new version (0.2.2) has been released. Please feel free to try out!

**Comment by fearcon-eap** [comment]
It's working! Thanks for the quick fix.
