### ISSUE TITLE
RuntimeError when result is shorter than specified limit

### ISSUE THREAD

**Issue by archletdaan** [sfu-db/connector-x#166]
When using a query that has a LIMIT clause where the result would be shorter than the specified LIMIT, a RuntimeError is thrown.
There are two slightly different cases:
1. when result set is empty the error is: `RuntimeError: Postgres EOF`
2. when result set is non-empty, but strictly shorter, the error is: `RuntimeError: connection closed`

How to reproduce:
use the following queries with a connection to a postgresql database
1. "select pid from pg_stat_activity where pid = -1 limit 2"
2. "select pid from pg_stat_activity where pid = (select pid from pg_stat_activity order by backend_start desc limit 1) limit 5"

We were expecting to get a result of length `min( len(<query without limit specified>), len(<query with limit specifiec>))` instead of an exception.

We can get around this currently by first doing a count query and only setting the limit to be max that result, however it would be nice of course if this could be handled on the connectorx side, since in postgresql this kind of query does not produce an error.

Our setting:
connectorx version = 0.2.0
postgresql version = 13.4

Thanks in advance!

**Comment by wangxiaoying** [comment]
Hi @archletdaan , thanks for reporting this issue with detailed info!

We are now directly allocating the returned pandas dataframe using limit as the number of rows, which would have the problem that you mentioned when limit value is smaller than real count. We will fix this issue in our next release (Nov 23rd). I can also make an alpha release if you need it earlier.

**Comment by archletdaan** [comment]
Hello @wangxiaoying , thanks for the quick reply and that is awesome news!
Thanks for offering an extra alpha release, for us that is not needed though, we can just wait a few days for the next official release.
