### ISSUE TITLE
Publish in conda

### ISSUE THREAD

**Issue by wangxiaoying** [sfu-db/connector-x#179]
https://github.com/sfu-db/connector-x/discussions/178

**Comment by timkpaine** [comment]
Can follow the same playbook we (eventually) sort out for polars

https://github.com/pola-rs/polars/issues/383
https://github.com/conda-forge/staged-recipes/pull/18906

**Comment by wangxiaoying** [comment]
Thank you @timkpaine ! These examples will be very useful.

**Comment by owenlamont** [comment]
I'd love to see ConnectorX on conda-forge. I just found Polars and was happy to see that was already on conda-forge then I started looking at the optional dependencies and realised I couldn't get ConnectorX (which also looks awesome) there yet...

**Comment by dhirschfeld** [comment]
https://github.com/conda-forge/connectorx-feedstock
