### ISSUE TITLE
how to pass odbc connection arguments to mssql? (using FreeTDS)

### ISSUE THREAD

**Issue by RMHogervorst** [sfu-db/connector-x#190]
Of course mssql is a being a difficult beast. but I'm using FreeTDS (Beccause I can't use the official microsoft connector). 

For sqlalchemy i could urlencode the information and pass that to sqlalchemy as a string.

```python
import urllib
quoted = urllib.parse.quote_plus("Driver={FreeTDS};Server=myserverlocation;Database=db;UID=name;PWD=password;TDS_version=1.1.6-1.1;Port=121212;")

connectionstring = "myssql+pyodbc://?odbc_connect={}".format(quoted)
```

And use that string in pandas `pd.read_sql('select top 10 * from dbo.stupidtablename', connectionstring )`

But this is not implemented for connector-x. 
What should I do in this case?

**Comment by wangxiaoying** [comment]
Hi @RMHogervorst , in `connectorx` we directly connect to mssql through underlying client driver. Unlike ODBC, it does not require you to install or configure anything on your machine. You can directly do like this:
```Python
import connectorx as cx

url = "mssql://user_name:password@server_host:port/db_name"
df = cx.read_sql(url, "select top 10 * from dbo.stupidtablename")
```

**Comment by RMHogervorst** [comment]
Ooooh damn!
That is much easier!
