### ISSUE TITLE
read_sql

### ISSUE THREAD

**Issue by hakantekbas** [sfu-db/connector-x#195]
Hi;

I have a simple question about  read_sql command. In pyodbc or other packages we're opening connection and then it is in our responsibility to close connection. How is connector_x controlling this process?

After I retrieve data with read_sql, is connection closed automatically? 

Thanks.

**Comment by wangxiaoying** [comment]
Hi @hakantekbas , connectorx is responsible for managing the connections. They will be automatically opened and then closed inside the read_sql function.

**Comment by hakantekbas** [comment]
@wangxiaoying thanks. for clarification.
