### ISSUE TITLE
Library not loaded: /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib

### ISSUE THREAD

**Issue by rraju26** [sfu-db/connector-x#197]
I am using python 3.9.6 installed from Anaconda on a Mac (OS Monterey 12.0.1). When I install connectorx using 

pip install connectorx 

and run 

import connectorx

get the following error:

Traceback (most recent call last):
File "<ipython-input-1-fb05477314b1>", line 1, in <module>
    import connectorx as cx
File "/Users/usrname/opt/anaconda3/envs/refpluspdf/lib/python3.9/site-packages/connectorx/__init__.py", line 3, in <module>
    from .connectorx_python import read_sql as _read_sql
ImportError: dlopen(/Users/usrname/opt/anaconda3/envs/refpluspdf/lib/python3.9/site-packages/connectorx/connectorx_python.cpython-39-darwin.so, 0x0002): Library not loaded: /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib
  Referenced from: /Users/usrname/opt/anaconda3/envs/refpluspdf/lib/python3.9/site-packages/connectorx/connectorx_python.cpython-39-darwin.so
  Reason: tried: '/usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib' (no such file), '/usr/local/lib/libssl.1.1.dylib' (no such file), '/usr/lib/libssl.1.1.dylib' (no such file)

I do have the library libssl.1.1.dylib in folders including /usr/lib/.  I did try creating the /openssl@1.1/lib/ folder. That didn't work either. The read_sql() function in pandas works well when I call it directly from pandas

Appreciate any help.

**Comment by rraju26** [comment]
Pls ignore - found a workaround by creating a new /user/local/lib directory.

**Comment by dovahcrow** [comment]
Thanks for posting the solution. This can definitely help other Mac users.
