### ISSUE TITLE
Fatal Python error: none_dealloc: deallocating None

### ISSUE THREAD

**Issue by TomEversdijk** [sfu-db/connector-x#201]
# The problem
Running a query will result in a `Fatal Python error: none_dealloc: deallocating None`.  I have no idea what causes this exception or how to even start looking what causes it. All help is appreciated.

# More context:
I am working on a [Dash](https://github.com/plotly/dash) application using [sqlalchemy](https://github.com/sqlalchemy/sqlalchemy) to construct the query which is them compiled for a mysql database. The query runs perfectly as expected (much faster the using the pandas build-in read_sql_query. `pd.read_sql_query(query, db.engine)`) but several seconds after the query, the entire python application crashes. When the query is not executed, the python application keeps running. When replacing the 2 lines below with the original pandas build-in read_sql_query, there is no problem and Python is not crashing at all.

# My Code
The query parameters is a complex dynamically created sqlalchemy select object of type `<class'sqlalchemy.sql.selectable.Select'>`. 

```Python
query_cx = str(query.compile(dialect=mysql.dialect(),compile_kwargs={"literal_binds": True}))
df = cx.read_sql(DB_URL, query_cx)
```

**Comment by wangxiaoying** [comment]
Hi @TomEversdijk , thanks for the info! However, I'm not so sure what caused the error here. Is it possible if you could provide a test case that we could reproduce the error? If not, maybe we need more details (e.g. will the application always crash when using connectorx on any query or just the sqlalchemy query? when does the application crash?). It will be better if we could narrow down the cause.

**Comment by Rishab1goelss** [comment]
Yes, I get the same error. I am using mysql connection and a very simple SELECT * query. I get the exact same error

**Comment by JerryRausk** [comment]
I can reproduce this error with this simple query (using AdventureWorks20219).

``` Python
import connectorx as cx

SQL_SERVER = "DESKTOP-BRA141K"
SQL_DB = "AdventureWorks2019"
SQL_QUERY = """
select *
from Sales.SalesOrderDetail sod
"""
sql_connection = f"mssql://{SQL_SERVER}/{SQL_DB}?trusted_connection=true"
df = cx.read_sql(conn = sql_connection, query = SQL_QUERY, return_type="pandas")
print(df.shape)
````
Which results in
```
(121317, 11)
Fatal Python error: none_dealloc: deallocating None       
Python runtime state: finalizing (tstate=000001A030CA2710)

Current thread 0x00003160 (most recent call first):       
<no Python frame>
```
Python version 3.9.1
These are my packages installed in this venv
```
Package         Version
connectorx      0.2.3
numpy           1.22.0
pandas          1.3.5
pip             20.2.3
pyodbc          4.0.32
python-dateutil 2.8.2
pytz            2021.3
setuptools      49.2.1
six             1.16.0
```

Please let me know if you need any more information.

**Comment by wangxiaoying** [comment]
> I can reproduce this error with this simple query (using AdventureWorks20219).
> 
> ```python
> import connectorx as cx
> 
> SQL_SERVER = "DESKTOP-BRA141K"
> SQL_DB = "AdventureWorks2019"
> SQL_QUERY = """
> select *
> from Sales.SalesOrderDetail sod
> """
> sql_connection = f"mssql://{SQL_SERVER}/{SQL_DB}?trusted_connection=true"
> df = cx.read_sql(conn = sql_connection, query = SQL_QUERY, return_type="pandas")
> print(df.shape)
> ```
> 
> Which results in
> 
> ```
> (121317, 11)
> Fatal Python error: none_dealloc: deallocating None       
> Python runtime state: finalizing (tstate=000001A030CA2710)
> 
> Current thread 0x00003160 (most recent call first):       
> <no Python frame>
> ```
> 
> Python version 3.9.1 These are my packages installed in this venv
> 
> ```
> Package         Version
> connectorx      0.2.3
> numpy           1.22.0
> pandas          1.3.5
> pip             20.2.3
> pyodbc          4.0.32
> python-dateutil 2.8.2
> pytz            2021.3
> setuptools      49.2.1
> six             1.16.0
> ```
> 
> Please let me know if you need any more information.

Thanks a lot for the test case! Could you please also provide the schema of the `Sales.SalesOrderDetail` table as well as a few sample data? That would be very helpful to reproduce the error.

**Comment by JerryRausk** [comment]
> 

@wangxiaoying absolutely! 

Since this is a table from AdventureWorks the documentation is available online, here is a summary of the table (link is for the 2014 version of AdventureWorks but I see no difference compared to the table in the 2019 version): https://www.sqldatadictionary.com/AdventureWorks2014/Sales.SalesOrderDetail.html

Below are some sample rows from the table, full table is part of the backup that is available from msft here: https://docs.microsoft.com/en-us/sql/samples/adventureworks-install-configure?view=sql-server-ver15&tabs=ssms
```
SalesOrderID	SalesOrderDetailID	CarrierTrackingNumber	OrderQty	ProductID	SpecialOfferID	UnitPrice	UnitPriceDiscount	LineTotal	rowguid					ModifiedDate
43659		1			4911-403C-98		1		776		1		2024,994	0,00			2024.994000	B207C96D-D9E6-402B-8470-2CC176C42283	2011-05-31 00:00:00.000
43659		2			4911-403C-98		3		777		1		2024,994	0,00			6074.982000	7ABB600D-1E77-41BE-9FE5-B9142CFC08FA	2011-05-31 00:00:00.000
43659		3			4911-403C-98		1		778		1		2024,994	0,00			2024.994000	475CF8C6-49F6-486E-B0AD-AFC6A50CDD2F	2011-05-31 00:00:00.000
43659		4			4911-403C-98		1		771		1		2039,994	0,00			2039.994000	04C4DE91-5815-45D6-8670-F462719FBCE3	2011-05-31 00:00:00.000
43659		5			4911-403C-98		1		772		1		2039,994	0,00			2039.994000	5A74C7D2-E641-438E-A7AC-37BF23280301	2011-05-31 00:00:00.000
43659		6			4911-403C-98		2		773		1		2039,994	0,00			4079.988000	CE472532-A4C0-45BA-816E-EEFD3FD848B3	2011-05-31 00:00:00.000
43659		7			4911-403C-98		1		774		1		2039,994	0,00			2039.994000	80667840-F962-4EE3-96E0-AECA108E0D4F	2011-05-31 00:00:00.000
43659		8			4911-403C-98		3		714		1		28,8404		0,00			86.521200	E9D54907-E7B7-4969-80D9-76BA69F8A836	2011-05-31 00:00:00.000
43659		9			4911-403C-98		1		716		1		28,8404		0,00			28.840400	AA542630-BDCD-4CE5-89A0-C1BF82747725	2011-05-31 00:00:00.000
43659		10			4911-403C-98		6		709		1		5,70		0,00			34.200000	AC769034-3C2F-495C-A5A7-3B71CDB25D4E	2011-05-31 00:00:00.000
```

Thanks alot for looking into this!

**Comment by wangxiaoying** [comment]
@JerryRausk @TomEversdijk @Rishab1goelss Thanks for reporting the issue. It turns out we missed to increase the reference count for None values. I have fixed it and release a new alpha version: `0.2.4-alpha.4`. Could you please download the new version and have a try?

**Comment by JerryRausk** [comment]
@wangxiaoying Can confirm that this testcase (and some other testing I've done) is resolved on 0.2.4-alpha.4! Thanks alot for the quick response!

**Comment by onacrame** [comment]
When is this version officially being released.  I'm having the same issue.

**Comment by wangxiaoying** [comment]
Hi @onacrame , our next stable release will be in later February.
