### ISSUE TITLE
MSSQL issues

### ISSUE THREAD

**Issue by ishbooisland** [sfu-db/connector-x#204]
Hi, 

It's possible I'm missing something, I'd really like to give this a try, but every time I try to connect to MSSQL I get this error:

---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
<ipython-input-140-81cbd350e272> in <module>
----> 1 df = cx.read_sql(conn=conn, query="Select * from test", partition_on="Unique_ID", partition_num=10)
      2 

C:\ProgramData\Miniconda3\lib\site-packages\connectorx\__init__.py in read_sql(conn, query, return_type, protocol, partition_on, partition_range, partition_num, index_col)
    100             raise ValueError("You need to install pandas first")
    101 
--> 102         result = _read_sql(
    103             conn,
    104             "pandas",

PanicException: byte index 1 is out of bounds of ``

My connection string that I'm passing to conn looks like:
mssql://user:passw@ip:port

I've updated pandas to the most recent version, and I upgraded connector-x from stable to alpha-5 to see if it made any difference. Thanks!

**Comment by wangxiaoying** [comment]
Hi @ishbooisland , I'm not so sure about where caused the error. Is it possible if you print the log of connector x like this example:

```Python
import os
os.environ["RUST_LOG"]="connectorx=debug,connectorx_python=debug"
import connectorx as cx

df = cx.read_sql(conn, query) // It will be more clear to test when no partitioning first
```

**Comment by ishbooisland** [comment]
After adding the logging line, I got this:

```
thread '<unnamed>' panicked at 'byte index 1 is out of bounds of ``', connectorx\src\sources\mssql\mod.rs:62:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File ".\test.py", line 9, in <module>
    df = cx.read_sql(conn=conn, query="Select * from test")
  File "C:\ProgramData\Miniconda3\lib\site-packages\connectorx\__init__.py", line 102, in read_sql
    result = _read_sql(
pyo3_runtime.PanicException: byte index 1 is out of bounds of ``
```

Since the error suggested setting the RUST_BACKTRACE, I did that as well and got the following with RUST_BACKTRACE set to full:

```
thread '<unnamed>' panicked at 'byte index 1 is out of bounds of ``', connectorx\src\sources\mssql\mod.rs:62:22
stack backtrace:
   0:     0x7ffdc6233b0f - PyInit_connectorx_python
   1:     0x7ffdc624aaca - rust_eh_personality
   2:     0x7ffdc622dff8 - PyInit_connectorx_python
   3:     0x7ffdc6236696 - PyInit_connectorx_python
   4:     0x7ffdc6236179 - PyInit_connectorx_python
   5:     0x7ffdc6236cd6 - PyInit_connectorx_python
   6:     0x7ffdc62368e1 - PyInit_connectorx_python
   7:     0x7ffdc623445f - PyInit_connectorx_python
   8:     0x7ffdc6236839 - PyInit_connectorx_python
   9:     0x7ffdc63b4970 - rust_eh_personality
  10:     0x7ffdc63b4f62 - rust_eh_personality
  11:     0x7ffdc5e722ae - PyInit_connectorx_python
  12:     0x7ffdc5e72d16 - PyInit_connectorx_python
  13:     0x7ffdc5d5d096 - <unknown>
  14:     0x7ffdc5d3932b - <unknown>
  15:     0x7ffdc5d7c7b0 - PyInit_connectorx_python
  16:     0x7ffdc5d7ba07 - PyInit_connectorx_python
  17:     0x7ffdd69cdf69 - PyArg_UnpackStack
  18:     0x7ffdd6a09446 - Py_CheckFunctionResult
  19:     0x7ffdd6a0be3e - PyEval_EvalFrameDefault
  20:     0x7ffdd6a06d18 - PyEval_EvalCodeWithName
  21:     0x7ffdd6a09a86 - Py_CheckFunctionResult
  22:     0x7ffdd6a0be3e - PyEval_EvalFrameDefault
  23:     0x7ffdd6a06d18 - PyEval_EvalCodeWithName
  24:     0x7ffdd6a17c6f - PyEval_EvalCodeEx
  25:     0x7ffdd6a17bcd - PyEval_EvalCode
  26:     0x7ffdd6a178fa - PyArena_New
  27:     0x7ffdd6a17889 - PyArena_New
  28:     0x7ffdd6a28230 - PyRun_FileExFlags
  29:     0x7ffdd6a2873f - PyRun_SimpleFileExFlags
  30:     0x7ffdd6ba4fff - PyRun_AnyFileExFlags
  31:     0x7ffdd6b4f375 - Py_FatalError
  32:     0x7ffdd6a2b9d8 - Py_RunMain
  33:     0x7ffdd6a2b861 - Py_RunMain
  34:     0x7ffdd6a2a716 - PyArgv_AsWstrList
  35:     0x7ffdd6af8fa5 - Py_Main
  36:     0x7ff621c41268 - <unknown>
  37:     0x7ffe273484d4 - BaseThreadInitThunk
  38:     0x7ffe27f31821 - RtlUserThreadStart
Traceback (most recent call last):
  File ".\test.py", line 10, in <module>
    df = cx.read_sql(conn=conn, query="Select * from test")
  File "C:\ProgramData\Miniconda3\lib\site-packages\connectorx\__init__.py", line 102, in read_sql
    result = _read_sql(
pyo3_runtime.PanicException: byte index 1 is out of bounds of ``
```

Thanks for your prompt help!

**Comment by wangxiaoying** [comment]
Hi @ishbooisland , thanks for the log! Looks like the error is caused by the none specified dbname. Our connection url requires a dbname on the path like this: `mssql://user:passw@ip:port/your_db_name`

**Comment by ishbooisland** [comment]
Thanks! That worked to get me moving. Performance is great, I do have one other issue that is popping up now, I can start a new thread if I need to. Basically, if I call:

```
df = cx.read_sql(conn=conn, query="Select * from test where [Column] = 'first")
df.to_csv('localfiledestination_first.csv')
```

Then call the same thing with a different where statement:

```
df = cx.read_sql(conn=conn, query="Select * from test where [Column] = 'second")
df.to_csv('localfiledestination_second.csv')
```

The python script exits right after connectorx reports "Writing Finished" on the second query
Here is the tail end of the log for the second query:

```
2021-12-22T15:15:30Z DEBUG connectorx::dispatcher] Allocate destination memory: 490575x65
2021-12-22T15:15:31Z DEBUG connectorx::dispatcher] Create destination partition
2021-12-22T15:15:31Z DEBUG connectorx::dispatcher] Start writing
2021-12-22T15:15:31Z DEBUG connectorx::dispatcher] Finalize partition 8
2021-12-22T15:15:31Z DEBUG connectorx::dispatcher] Partition 8 finished
2021-12-22T15:15:31Z DEBUG connectorx::dispatcher] Finalize partition 7
2021-12-22T15:15:31Z DEBUG connectorx::dispatcher] Partition 7 finished
2021-12-22T15:15:31Z DEBUG connectorx::dispatcher] Finalize partition 6
2021-12-22T15:15:31Z DEBUG connectorx::dispatcher] Partition 6 finished
2021-12-22T15:15:31Z DEBUG connectorx::dispatcher] Finalize partition 3
2021-12-22T15:15:32Z DEBUG connectorx::dispatcher] Partition 3 finished
2021-12-22T15:15:32Z DEBUG connectorx::dispatcher] Finalize partition 5
2021-12-22T15:15:32Z DEBUG connectorx::dispatcher] Partition 5 finished
2021-12-22T15:15:32Z DEBUG connectorx::dispatcher] Finalize partition 1
2021-12-22T15:15:32Z DEBUG connectorx::dispatcher] Partition 1 finished
2021-12-22T15:15:33Z DEBUG connectorx::dispatcher] Finalize partition 4
2021-12-22T15:15:34Z DEBUG connectorx::dispatcher] Partition 4 finished
2021-12-22T15:15:37Z DEBUG connectorx::dispatcher] Finalize partition 2
2021-12-22T15:15:38Z DEBUG connectorx::dispatcher] Partition 2 finished
2021-12-22T15:15:38Z DEBUG connectorx::dispatcher] Finalize partition 0
2021-12-22T15:15:38Z DEBUG connectorx::dispatcher] Partition 0 finished
2021-12-22T15:15:41Z DEBUG connectorx::dispatcher] Finalize partition 9
2021-12-22T15:15:42Z DEBUG connectorx::dispatcher] Partition 9 finished
2021-12-22T15:15:42Z DEBUG connectorx::dispatcher] Writing finished
fatal Python error: deallocating None
python runtime state: initialized

current thread 0x0000c00c (most recent call first):
 File "./test.py", line 70 in <module>
```

I've noticed that if I instead assign each call a new variable (df1, df2, df3 etc...), it will run without any issues, it seems to only happen if overwriting a previously used "df" object.

Again, thanks for your prompt responses, so far this is great.

**Comment by wangxiaoying** [comment]
Hi @ishbooisland , thanks for reporting this issue! It might be related to the issue https://github.com/sfu-db/connector-x/issues/201 . We will take a look at it.

**Comment by wangxiaoying** [comment]
Hi @ishbooisland , I've been trying to investigate this issue but I cannot reproduce the error in my local environment. Could you please provide more information, such as:
* Python version you are using
* What environment you found this error (script? jupyter notebook?)
* Does this error always occur no matter how the query looks like? And no matter using or not using partition?
* Does this error occurs even if you don't write the dataframe to csv?

Also, if it is possible, could you try to return an arrow dataframe (set `return_type="arrow"`) and use its [write_csv](https://arrow.apache.org/docs/python/generated/pyarrow.csv.write_csv.html#pyarrow.csv.write_csv) to do the same workload? It could help us identify whether the issue is only in pandas or all dataframes.

**Comment by wangxiaoying** [comment]
Redirecting error `fatal Python error: deallocating None` to https://github.com/sfu-db/connector-x/issues/201
