### ISSUE TITLE
Suppress 'get partition query' when calling cx.read_sql (Python)

### ISSUE THREAD

**Issue by chris-gaia-lens** [sfu-db/connector-x#217]
Hi, 

Thanks for the excellent package.

There doesn't seem to be an option for suppressing the output for the partition queries using cx.read_sql

``` 
df = cx.read_sql(pg_conn_str, 'select * from tbl limit 10',
        partition_on=id, partition_num=2)
```
will always produce (e.g.) output

```
get partition query: "SELECT * FROM (SELECT * FROM tbl LIMIT 10) AS CXTMPTAB_PART WHERE 18511 <= CXTMPTAB_PART.id AND CXTMPTAB_PART.id< 18810"
get partition query: "SELECT * FROM (SELECT * FROM tbl LIMIT 10) AS CXTMPTAB_PART WHERE 18810 <= CXTMPTAB_PART.id AND CXTMPTAB_PART.id< 19110"
```

This becomes overwhelming in logs when running on many tables with many partitions

Any help much appreciated

**Comment by wangxiaoying** [comment]
Hi @chris-gaia-lens , can you try the latest alpha version (0.2.4-alpha.4) of connectorx? I think this message should be removed.

**Comment by chris-gaia-lens** [comment]
Thanks! That worked
