### ISSUE TITLE
Update polars and arrow2 to latest versions

### ISSUE THREAD

**Issue by glennpierce** [sfu-db/connector-x#221]
I am currently wanting to get a dataframe back in polars format and then beable to call pivot on it but
the pivot function does not exist in 0.18 version of polars. Can we update to the latest for these formats please.

Thanks

**Comment by wangxiaoying** [comment]
It looks like arrow2 has some breaking changes in [0.9](https://github.com/jorgecarleitao/arrow2/releases/tag/v0.9.0) that we need to support accordingly. Will add this to our next milestone (Feb 28th). Also, please feel free to submit a PR if you like in the meanwhile.

**Comment by wangxiaoying** [comment]
https://github.com/sfu-db/connector-x/pull/234
