### ISSUE TITLE
Oracle read_sql can't parse select in join

### ISSUE THREAD

**Issue by wKollendorf** [sfu-db/connector-x#226]
Hello,
when trying to query an oracle DB, where the joined table is a result of a subselect, the operation fails.
Example query:
```
...
FROM HED_FS_HEAD
left join
      DEP_FS_ABW on HED_FS_HEAD.id = DEP_FS_ABW.id and DEP_FS_ABW.dsnr = 1
cross join
      ( select level as ABW_ORDER from dual connect by level <= 30 ) h
where
      HED_FS_HEAD.ewbnr_wbnr in [1, 2, 3]
```

message:
`sql parser error: Expected joined table, found: .`

When the cross join part is removed, the query is working. The original query is working, when using it with other  tools.

**Comment by wangxiaoying** [comment]
Hi @wKollendorf , can you try the new alpha version `0.2.4-alpha.8`? Currently the [sqlparser](https://github.com/sqlparser-rs/sqlparser-rs) we use does not support oracle dialect, so we need to hard code the sqls that we manually constructed the sql queries we need to issue to oracle (commit: https://github.com/sfu-db/connector-x/commit/87829032d788c6fbd04f8c26775cd26d4f328719).

**Comment by wKollendorf** [comment]
With version 0.2.4 the error is gone!
