### ISSUE TITLE
Oracle read_sql: invalid digit found in string

### ISSUE THREAD

**Issue by wKollendorf** [sfu-db/connector-x#227]
Hello,

when using e.g. pyodbc the query is working. The same one throws this error message when using connectorx:

`invalid digit found in string`

Unfortunately I can't reproduce it with a simple example, because the message doesn't really give me much information. Is there a way to debug it in more detail? 

Thanks

**Comment by wangxiaoying** [comment]
Hi @wKollendorf , could you please provide more details (would be better to focus on the result column that causes the error)? Such as the data type, is there any aggregation used to generate the column, what does the query result looks like?

**Comment by wKollendorf** [comment]
Sorry for the late answer. 

I could narrow it down to the round() function. The query looks like this:

```
select
   id
   round(value*1000,2) value
from
   sometable
where
   id = 1000
```

**Comment by wangxiaoying** [comment]
Hi @wKollendorf , have you tried the newest version `0.2.4` on this query? I cannot reproduce this error. Here is how I constructed the query locally:
<img width="929" alt="image" src="https://user-images.githubusercontent.com/5569610/156970792-228cc5d5-20b4-4dc6-9fa4-f98ba8722ec0.png">

where the table looks like this:
<img width="901" alt="image" src="https://user-images.githubusercontent.com/5569610/156970940-bbed9a21-a20b-49f3-bf9c-0d808fb3f322.png">

**Comment by wKollendorf** [comment]
The column type is BINARY_FLOAT.

Example with BINARY_FLOAT:

val = 1.1
round(val, 2) -> invalid digit found in string

val = 1.1
round(val, 0) -> OK

val = 1
round(val, 2) -> OK

**Comment by wangxiaoying** [comment]
Hi @wKollendorf , sorry for the late rely. Can you try the newest version `0.2.5` to see whether it works on your case?

**Comment by wKollendorf** [comment]
Version 0.2.5 is working. Thanks a lot!
