### ISSUE TITLE
How do I connect to Oracle?

### ISSUE THREAD

**Issue by Fatroundfox** [sfu-db/connector-x#232]
I keep getting this error message. Any idea what might be wrong? My login credentials and DSN are all correct. tsnnames.ora file are also in the environment variable. However, I just cannot connect.

**This is what I currently have:**
import connectorx as cx

conn = f"oracle://username:mypassword!001@dsn"
query = 'select * from table"

data = cx.read_sql(conn , query=query)

**This is the error message:**
"timed out waiting for connection: OCI Error: ORA-12154: TNS:could not resolve the connect identifier specified"

**Comment by wangxiaoying** [comment]
Hi @Fatroundfox , the separator of DSN should be "/" instead of "@", the connection string should look like this:
```
oracle://${ORACLE_USER}:${ORACLE_PASSWORD}@${ORACLE_HOST}:${ORACLE_PORT}/${ORACLE_DB}
```

**Comment by Fatroundfox** [comment]
Hi, already changed the format to oracle://${ORACLE_USER}:${ORACLE_PASSWORD}@${ORACLE_HOST}:${ORACLE_PORT}/${ORACLE_DB}, but I am still getting the same error message.

**Comment by wangxiaoying** [comment]
Hi @Fatroundfox , can you try to use command line tool like `sqlplus` on the same machine to see whether it can connect to the database? Here is the example command:
```
sqlplus ${ORACLE_USER}/${ORACLE_PASSWORD}@${ORACLE_HOST}:${ORACLE_PORT}/${ORACLE_DB}
```

**Comment by wangxiaoying** [comment]
Hi @LifeHuntX , looks like your machine is not reachable from the client machine since `sqlplus` also shows the same message.

**Comment by LifeHuntX** [comment]
Oddly enough, when i use cx_Oracle package, or sql developer i can connect fine. But this method gives me no TNS:listener error. Would highly appreciate any help on that.

**Comment by LifeHuntX** [comment]
I upgraded to 0.2.4 and the issue is solved, can connect now.
