### ISSUE TITLE
Connect to Clickhouse

### ISSUE THREAD

**Issue by moheikal79** [sfu-db/connector-x#256]
Hi
Please for your support to connect to Clickhouse. I have used the following codes and unfortunately it doesn't work.

df= cx.read_sql("clickhouse://yourname:yourpassword@127.0.0.1:8123/default", "SELECT * FROM data_source")

df= cx.read_sql("clickhouse://yourname:yourpassword@localhost:8123/default", "SELECT * FROM data_source")

df= cx.read_sql("mysql://yourname:yourpassword@127.0.0.1:8123/default", "SELECT * FROM data_source")

df= cx.read_sql("mysql://yourname:yourpassword@localhost:8123/default", "SELECT * FROM data_source")

Regards

**Comment by wangxiaoying** [comment]
Hi @moheikal79 , which version are you using? Can you check whether this related discussion help you: https://github.com/sfu-db/connector-x/discussions/165#discussioncomment-2118825 ?

**Comment by moheikal79** [comment]
Thanks @wangxiaoying,  it is working fine now, I had to change the port to 9004 (mysql port in clickhouse) instead of 8123.

df= cx.read_sql("clickhouse://yourname:yourpassword@127.0.0.1:9004/default", "SELECT * FROM data_source")
