### ISSUE TITLE
Can we upgrade the version of the `arrow`?

### ISSUE THREAD

**Issue by zemelLeong** [sfu-db/connector-x#257]
I use `connector-x` and `datafusion` got this error.
```
mismatched types
expected reference `&Vec<datafusion::arrow::record_batch::RecordBatch>`
   found reference `&Vec<arrow::record_batch::RecordBatch>`
perhaps two different versions of crate `arrow` are being used?rustc[E0308](https://doc.rust-lang.org/error-index.html#E0308)
```
Detail info: [https://github.com/apache/arrow-datafusion/issues/2090](https://github.com/apache/arrow-datafusion/issues/2090)

**Comment by houqp** [comment]
@zemelLeong the upgrade should be pretty straight forward, let me know if you need any help with this.

**Comment by zemelLeong** [comment]
> @zemelLeong the upgrade should be pretty straight forward, let me know if you need any help with this.

I'll try it today.

**Comment by wangxiaoying** [comment]
Hi @zemelLeong  sorry for the late reply. I just upgraded the `arrow` version to 9.0.0 (the same with with current `datafusion` [release](https://crates.io/crates/datafusion/7.0.0/dependencies)).

I also found that the main branch of `datafusion` is 11 so this version might need to be upgraded again. Please feel free to submit a PR if you need it later. Basically you need to set up the version at both [here](https://github.com/sfu-db/connector-x/blob/main/connectorx/Cargo.toml#L21) and [here](https://github.com/sfu-db/connector-x/blob/main/connectorx-python/Cargo.toml#L14).
