### ISSUE TITLE
There seems to be something wrong with the document

### ISSUE THREAD

**Issue by zemelLeong** [sfu-db/connector-x#260]
This code if has the prefix `sqlite://` will be got an error `unable to open database file: sqlite://......`. If remove prefix it will be ok.
https://github.com/sfu-db/connector-x/blob/d87f37f434cc286d3e7c22cd0b5714d13452fbb0/connectorx/src/lib.rs#L97

```rust
#[test]
fn sqlite_source() {
    let queries = &["SELECT * FROM uk_cities"];
    let source = SQLiteSource::new("sqlite://sqlite.db", 2).unwrap();
    let mut destination = ArrowDestination::new();
    let dispatcher = Dispatcher::<
        SQLiteSource,
        ArrowDestination,
        SQLiteArrowTransport,
    >::new(source, &mut destination, queries, None);
    dispatcher.run().unwrap();
    println!("{:#?}", destination.arrow());
}
```

![image](https://user-images.githubusercontent.com/26835087/161423326-d786043c-5380-4722-976a-c3e56a7d0be2.png)
![image](https://user-images.githubusercontent.com/26835087/161423343-944bef42-4c65-4322-87ee-206314c5f7e6.png)

**Comment by wangxiaoying** [comment]
Hi @zemelLeong , thanks for pointing out! Indeed, this doc is out of date. Will fix it.
