### ISSUE TITLE
Arrow2: No conversion rule from Blob(true) for Arrow2TypeSystem

### ISSUE THREAD

**Issue by Kipriz** [sfu-db/connector-x#261]
I'm trying to use connectorx to read data from MySQL and mssql.
When I used return_type "arrow" I got truncated datetimes for all timestamps and datetimes columns.
To resolve this issue, I switched to "arrow2" type as suggested here https://github.com/sfu-db/connector-x/issues/229
However, I faced with another exception when reading a column with "text" type from MySql database:
```
RuntimeError: No conversion rule from Blob(true) to connectorx::destinations::arrow2::typesystem::Arrow2TypeSystem.
```

Any suggestions how to deal with this issue?

Code sample:
```
conn = "mysql://user:password@localhost:3306/control_panel"
sql = """
select id, name, created_at, contact from cfg_rds_connection
"""
df = cx.read_sql(conn, sql, return_type="arrow2")
pq.write_table(df, './parquet/cfg_rds_connection_pyarrow_ts.parquet')
```
`contact` column has type `text`.

**Comment by wangxiaoying** [comment]
Hi @Kipriz , thanks for pointing out. Indeed we missed this transport rule for mysql to arrow and just fixed it in https://github.com/sfu-db/connector-x/commit/1d28e5abff47f78c2831a8336def88de08571de0. We are making an alpha release for this fix, will let you know when it's done.

**Comment by wangxiaoying** [comment]
Hi @Kipriz , the alpha version is ready. Can you try to install  version `0.2.6a1` and see whether it works?

**Comment by Kipriz** [comment]
@wangxiaoying Thank you for such a quick fix! It works!
