### ISSUE TITLE
Cannot read mysql correctly if password has "#" character

### ISSUE THREAD

**Issue by yosef-cupist** [sfu-db/connector-x#267]
If my MySQL password has this "#" character at the first position, connectorx cannot recognize the host correctly.

For example: 
My MySQL connection likes this
- Host: database_host:3306
- User: admin
- Password: #mypassword

Python code:

```
import connectorx as cx
db_uri = "mysql://admin:#mypassword@database_host:3306/test"
cx.read_sql(db_uri, "select * from users limit 100")
```

The above code will raise an error when running:

```
[2022-04-11T01:50:25Z ERROR r2d2] DriverError { Could not connect to address `admin:3306': failed to lookup address information: Name or service not known }
[2022-04-11T01:50:26Z ERROR r2d2] DriverError { Could not connect to address `admin:3306': failed to lookup address information: Name or service not known }
```

**Comment by wangxiaoying** [comment]
Hi @yosef-cupist , can you apply url encode on your password and try whether it works? For example:

```
import urllib.parse
db_uri = f"mysql://admin:{urllib.parse.quote('#mypassword')}@database_host:3306/test"
```

**Comment by yosef-cupist** [comment]
@wangxiaoying It worked if I used your method. Thank you. But I think you should fix this because other libraries (SQLAlchemy) don't need this.
