### ISSUE TITLE
Add CLOB and BLOB to Oracle typesystem

### ISSUE THREAD

**Issue by wKollendorf** [sfu-db/connector-x#274]
#### Describe your feature request

Got "not implemented: hahaha Clob" when trying to query a table with column of type CLOB....

Thanks for your effort!

**Comment by wangxiaoying** [comment]
Hi @wKollendorf , thanks for the report! We will add the support for these types. Sorry for the inconvenience.

**Comment by wangxiaoying** [comment]
Hi @wKollendorf I saw you added these types in your local fork? Do you want to submit a PR for this?

**Comment by wangxiaoying** [comment]
Hi @wKollendorf , thanks for the PR. We have merged it and released newest alpha version: `0.3.1a1`, which should be available when this workflow is done: https://github.com/sfu-db/connector-x/actions/runs/2322874507
