### ISSUE TITLE
PyPI page does not have a license specified

### ISSUE THREAD

**Issue by florianjuesten** [sfu-db/connector-x#310]
Hi :) 
This page https://pypi.org/project/connectorx/ does not have the MIT license specified currently. A lot of people (including us) are using license checkers before releasing their software. Our tool is currently failing because connectorx does not have a license specified. 
Could you please add the license to the page?

Best
Flo

**Comment by wangxiaoying** [comment]
Hi @florianjuesten sorry for the delay. We have added the license to pypi now for the newest version https://pypi.org/project/connectorx/0.3.1a3/
