### ISSUE TITLE
Can't connect to MSSQL

### ISSUE THREAD

**Issue by SergKS8** [sfu-db/connector-x#320]
The problem is that
when I'm trying to read data from MSSQL like this:
conn = f'mssql://{login}:{password}@{host}/{database}'
cx.read_sql(conn, sql_aims)

I'm getting the error
RuntimeError: parse error: invalid port number.
But default port = 1433 is a valid port.

But if I changed the password in conn string to combination without symbol '#' I get another arror -
RuntimeError: Timed out in bb8.
I think that thing is that my password contain specific symbol # and this is the cфuse of the error.
How can I read data from MSSQL with connectorx in such a case?

The SOURSE - MS SQL Server with SQL Server Authentication.

**Comment by wangxiaoying** [comment]
Follow up in https://github.com/sfu-db/connector-x/discussions/319
