### ISSUE TITLE
[postgres] Unexplicable `ERROR: syntax error at or near ";"`

### ISSUE THREAD

**Issue by baggiponte** [sfu-db/connector-x#330]
#### What language are you using?

**Python**

#### What version are you using?

0.3.0

#### What database are you using?

PostgreSQL

#### What dataframe are you using?

Polars, Pandas

#### Can you describe your bug?

The same query does not run with connector-x but works with pandas & sqlalchemy + psycopg2 or standalone psycopg3.

#### What are the steps to reproduce the behavior?

Can provide a small db dump if needed

##### Example query / code

```python
connection_uri = f"postgresql://{user}:{password}@{host}:{port}/{database}"
query = "SELECT b.bici FROM bikemi_data b LIMIT 100;"

# this works
import pandas as pd
df = pd.read_sql(query, connection_uri) 
df.head()

# this fails; note: same uri & query
import connectorx as cx
data = cx.read_sql(connection_uri, query)
data.head()
```

#### What is the error?

> Traceback (most recent call last):
  File "/Users/luca/Documents/dev/python-projects/bikemi/.venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-becea215df54>", line 4, in <cell line: 4>
    data_pd = cx.read_sql(connection_uri, query, return_type="pandas")
  File "/Users/luca/Documents/dev/python-projects/bikemi/.venv/lib/python3.9/site-packages/connectorx/__init__.py", line 224, in read_sql
    result = _read_sql(
RuntimeError: db error: ERROR: syntax error at or near ";"

**Comment by wangxiaoying** [comment]
Hi @baggiponte , can you remove the ";" and try again? We only support single query for `read_sql` so there is no need to add ";"

**Comment by baggiponte** [comment]
Hi @wangxiaoying and thanks for the prompt reply! Indeed that's the solution. I did not notice there was no ";" in the sample queries in the docs. connector-x is so great!
