### ISSUE TITLE
not support jsonb when read_sql postgre table to arrow

### ISSUE THREAD

**Issue by wonb168** [sfu-db/connector-x#331]
I use duckdb as OLAP plugin for postgre.
I need export data from pg to duckdb, and there have jsonb column in my pg table, when I use connectorx to read_sql to arrow, raise error:
RuntimeError: No conversion rule from JSONB(true) to connectorx::destinations::arrow::typesystem::ArrowTypeSystem.
So，I want：
1. support jsonb when etl pg to arrow (duckdb can read arrow)
2. directly add duckdb as return_type for read_sql()

**Comment by wangxiaoying** [comment]
Hi @wonb168 , thanks for the issue. For jsonb, can you try to set the return type as `arrow2`?

For adding `duckdb`, I think it will be the same with supporting `to_sql` https://github.com/sfu-db/connector-x/discussions/213, will add your request into the discussion.

**Comment by wonb168** [comment]
but int[] in my greeplun(int array column,like {1,2,3}) etl to arrow2 also error:
RuntimeError: No conversion rule from Int4Array(true) to connectorx::destinations::arrow::typesystem::ArrowTypeSystem.
