### ISSUE TITLE
How to add 'appname' to mssql connection?

### ISSUE THREAD

**Issue by italanchan** [sfu-db/connector-x#336]
For easy to track sql script from sql profiler, we use application name to check.

How to add 'appname' to mssql connection using connectionx ?

**Comment by wangxiaoying** [comment]
Hi @italanchan , we just added the support for appname. Can you try `pip install connectorx==0.3.1a5` and construct the connection string like: `mssql://{user}:{password}@{host}:{port}/{db}?appname={appname}` and see whether it works?
