### ISSUE TITLE
PostgresSource panic when nconn is less than number of partitions

### ISSUE THREAD

**Issue by ghais** [sfu-db/connector-x#340]
#### What language are you using?

Rust

#### What version are you using?

0.3.1-alpha.1

#### What database are you using?

PostgreSQL

#### What dataframe are you using?

Arrow2

#### Can you describe your bug?

Panic when PostgresSource pool size is less than the number of partitions .

The issue seems to be coming from the fact that each partition is moving a connection and not using it until each partition is assigned a connection. This means that we are always guaranteed to panic.

#### What are the steps to reproduce the behavior?

Construct ```PostgresSource::<BinaryProtocol, NoTls>::new(psql_config, NoTls, 1)```

Then create a dispatcher which needs two partitions

##### Database setup if the error only happens on specific data or data type

Table schema and example data

##### Example query / code

```rust
let mut destination = Arrow2Destination::new();
let mut psql_config = postgres::Config::new();

psql_config
        .user("user")
        .password("pass")
        .host("localhost")
        .dbname("test")
        .port(5432);

let source : PostgresSource<BinaryProtocol, NoTls> = PostgresSource::<BinaryProtocol, NoTls>::new(psql_config, NoTls, 1).unwrap();

let queries = &["SELECT * FROM db WHERE id < 100", "SELECT * FROM db WHERE id >= 100"];

let dispatcher = Dispatcher::<PostgresSource<BinaryProtocol, NoTls>, Arrow2Destination, PostgresArrow2Transport<BinaryProtocol, NoTls>>::new(source, &mut destination, &queries, None);
   
dispatcher.run().expect("run failed");
```

#### What is the error?

```
thread 'main' panicked at 'run failed: Source(PostgresPoolError(Error(None)))', QRunner/src/main.rs:91:22
```

**Comment by wangxiaoying** [comment]
Hi @ghais , this is not a bug. We need to require the pool size to be larger than or equal to the number of partitioned queries otherwise there is no meaning to partitioning the query. We should have put it into the [documentation](https://github.com/sfu-db/connector-x/commit/9f7e36e9373768fce39439cfc19cd249d1074d93) though. Sorry for the misleading and thanks for the reminder.
