### ISSUE TITLE
getting RuntimeError: Timed out in bb8. maybe because of special characters in query?

### ISSUE THREAD

**Issue by MuhammadPathan** [sfu-db/connector-x#348]
The connection details are correct since I have tested using pyodbc and everything was working fine. 

no special characters in the connection string 
conn=f"mssql://{username}:{password}@{host}:{port}/{db}"

however, I have special characters in query for example doing something like this:

query="SELECT * from ViewSchema.my_view_  WHERE RecordTime > '2022-08-29 12:14:16.290' "
data = pl.read_sql(query,conn) 

full error 

 data = pl.read_sql(query,conn) 
  File "C:\Users\myname\AppData\Local\Programs\Python\Python38\lib\site-packages\polars\io.py", line 1057, in read_sql
    tbl = cx.read_sql(
  File "C:\Users\myname\AppData\Local\Programs\Python\Python38\lib\site-packages\connectorx\__init__.py", line 257, in read_sql
    result = _read_sql(       
RuntimeError: Timed out in bb8

maybe because the view name has underscores and a dot symbol? any help to fix this greatly appreciated

**Comment by wangxiaoying** [comment]
Hi @MuhammadPathan , I think this error means connectorx cannot connect to the database. You can try a simple query without special characters and I assume the error remains the same.

For mssql, we support enabling `encrypt` like mentioned [here](https://sfu-db.github.io/connector-x/databases/mssql.html). You can try whether enabling it can make it work. If not, you can also test using other client tools like `mssql-cli` to see whether they are able to connect to your database using username and password. This may help us to know whether it is the issue of connectorx or some configuration requirement of mssql.

**Comment by MuhammadPathan** [comment]
Thanks, enabling encrypt solved the problem
