### ISSUE TITLE
RuntimeError: No conversion rule from Int4Array(true) to connectorx::destinations::arrow::typesystem::ArrowTypeSystem.

### ISSUE THREAD

**Issue by wonb168** [sfu-db/connector-x#352]
#### What language are you using?

 **Python**.

#### What version are you using?

0.3.0

#### What database are you using?

greenplum

#### What dataframe are you using?

Arrow and Arrow2

#### Can you describe your bug?

when db has array column, then read_sql raise error:
RuntimeError: No conversion rule from Int4Array(true) to connectorx::destinations::arrow::typesystem::ArrowTypeSystem.

#### What are the steps to reproduce the behavior?

import connectorx as cx
sql="""select * from tenant_baosheng_adm.adm_store_display_limit_parameter"""
df_cx=cx.read_sql(con_pg, sql,return_type='arrow')
# df_cx=cx.read_sql(con_pg, sql,return_type='arrow2')

##### Database setup if the error only happens on specific data or data type

int[] and jsonb column in greenplum(postgresql)

##### Example query / code

```
import connectorx as cx
sql="""select * from tenant_baosheng_adm.adm_store_display_limit_parameter"""
df_cx=cx.read_sql(con_pg, sql,return_type='arrow')
# df_cx=cx.read_sql(con_pg, sql,return_type='arrow2')
```

#### What is the error?

RuntimeError: No conversion rule from Int4Array(true) to connectorx::destinations::arrow::typesystem::ArrowTypeSystem.

**Comment by wangxiaoying** [comment]
Hi @wonb168 , this is the same issue with https://github.com/sfu-db/connector-x/issues/339 that we don't support array type for arrow right now. I will redirect to that original issue.
