### ISSUE TITLE
connect oracle error

### ISSUE THREAD

**Issue by heyuqi1970** [sfu-db/connector-x#353]
I connect to oracle find error
`[2022-09-15T09:10:38Z ERROR r2d2] DPI Error: DPI-1047: Cannot locate a 64-bit Oracle Client library: "dlopen(libclntsh.dylib, 1): image not found". See https://oracle.github.io/odpi/doc/installation.html#macos for help`

```
import connectorx as cx
url = f'oracle://xxx:xx@xxxx:1521/dx'
query = "select * from region"
cx.read_sql(url, query)
```

os: macos Bigsur
python:3.97
connector-x: 0.3.1a6

**Comment by djfrancesco** [comment]
Dear @heyuqi1970, I had a similar issue. I installed the Oracle [Client ](https://www.oracle.com/fr/database/technologies/instant-client/downloads.html) and it worked fine then. Otherwise you can use [oracledb](https://oracle.github.io/python-oracledb/), but it won't be as efficient I guess...

**Comment by heyuqi1970** [comment]
@djfrancesco 
Thanks for your help！ As you suggested，it worked.

**Comment by bnewman-tech** [comment]
Hello! 

Are you able to use [oracledb](https://oracle.github.io/python-oracledb/) thin mode driver with [connector-x](https://github.com/sfu-db/connector-x) without installing the Oracle Client? Any suggestions are appreciated!
```
import connectorx as cx

ENGINE_PATH = "oracle+oracledb://username:password@host:post/service_name"
query = "select * from table"  # query string

cx.read_sql(ENGINE_PATH, query)
```

Getting this error:
```
[2023-11-01T02:17:30Z ERROR r2d2] DPI Error: DPI-1047: Cannot locate a 64-bit Oracle Client library:
"dlopen(libclntsh.dylib, 0x0001): tried: 'libclntsh.dylib' (no such file),
'/System/Volumes/Preboot/Cryptexes/OSlibclntsh.dylib' (no such file), '/usr/lib/libclntsh.dylib' 
'(no such file, not in dyldcache), 'libclntsh.dylib' (no such file), '/usr/lib/libclntsh.dylib' 
(no such file, not in dyld cache)". See https://oracle.github.io/odpi/doc/installation.html#macos for help
```
