### ISSUE TITLE
RuntimeError: Server requested a connection to an alternative address

### ISSUE THREAD

**Issue by MuhammadPathan** [sfu-db/connector-x#360]
posted full question on stackoverflow

https://stackoverflow.com/questions/73812209/connectorx-server-requested-a-connection-to-an-alternative-address-in-azure-pipe

connecting to sql server using connectorx and polars. everything works correctly locally and not getting any errors. however, when using azure pipelines to run code getting the following error "result = _read_sql(RuntimeError: Server requested a connection to an alternative address":

This doesn't make sense since the exact same details worked locally but does not work in pipeline?

internal files which error is caused:

File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\polars\io.py", line 1095, in read_sql tbl = cx.read_sql( File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\connectorx_init_.py", line 257, in read_sql

**Comment by kykyi** [comment]
Your SO post references your environment vars which can't be seen. Are you sure these are configured correctly?

**Comment by MuhammadPathan** [comment]
Yeah, environment vars are correct. Found out the error its because of partitioning. might be a database issue rather than connectorx. partitioning works locally but not in the pipeline am guessing something to do with permissions and threads.

#causes error
 data=pl.read_sql(query, conn, partition_on="Partition", partition_num=10)
#no error
 data=pl.read_sql(query, conn)

**Comment by wangxiaoying** [comment]
> @kykyi Yeah, environment vars are correct. Found out the error its because of partitioning. might be a database issue rather than connectorx. partitioning works locally but not in the pipeline am guessing something to do with permissions and threads.
> 
> #causes error data=pl.read_sql(query, conn, partition_on="Partition", partition_num=10) #no error data=pl.read_sql(query, conn)

Yeah, when partition is enabled, connectorx will establish multiple connections so it can issue multiple partitioned queries concurrently to speed up the data fetching process. And it seems like the database server does not allow to do this.
