### ISSUE TITLE
Add pyarrow as destination

### ISSUE THREAD

**Issue by wangxiaoying** [sfu-db/connector-x#37]
* return pyarrow (from arrow) if user ask arrow as destination

**Comment by dovahcrow** [comment]
Hi @ritchie46 , may I ask if you are currently working on adding PyArrow support? Since I'd like to include PyArrow as well in the 0.2 release, maybe I can take it over if you haven't started the work.

**Comment by ritchie46** [comment]
Oh no, I haven' started yet. Here is the code for the pyarrow interop with Pyo3 that I use in Polars. https://github.com/pola-rs/polars/tree/master/py-polars/src/arrow_interop

I hope it is any help.

**Comment by dovahcrow** [comment]
@ritchie46 Thanks! I'll definitely take a look.

**Comment by dovahcrow** [comment]
Hi @ritchie46 I implemented the PyArrow support, as well as direct outputting Polars dataframe.

Do it in rust:
https://github.com/sfu-db/connector-x/blob/main/connectorx/tests/test_polars.rs

Do it in Python:
https://github.com/sfu-db/connector-x/blob/main/connectorx-python/connectorx/tests/test_polars.py

**Comment by ritchie46** [comment]
This is great! I will add connectorX in the documentation and use it in the python bindings.

For the moment it is only postgres, right?

**Comment by dovahcrow** [comment]
@ritchie46 It's Postgres/MySQL/Sqlite as well as other databases with a compatible protocol (e.g. Clickhouse uses MySQL protocol, redshift uses Postgres protocol).

https://github.com/sfu-db/connector-x#sources
