### ISSUE TITLE
Getting "Panicked at 'not implemented: citext'"

### ISSUE THREAD

**Issue by Sirsirious** [sfu-db/connector-x#372]
#### What language are you using?

Python 🐍 

#### What version are you using?

Tested 0.3.0 and alpha 0.2.5 (Mac M1 release)

#### What database are you using?

Postgres

#### What dataframe are you using?

Pandas

#### Can you describe your bug?

When trying to:
```python
cx.read_sql(postgres_url, query)
```
I get:
```thread '<unnamed>' panicked at 'not implemented: citext', /Users/runner/work/connector-x/connector-x/connectorx/src/sources/postgres/typesystem.rs:100:22```

Same URL and Query has been used with default pandas read_sql and I didn't have any issue.

I'm on a Macbook Pro 2020 M1

OS Version: MacOs Monterey 12.5.1

<img width="587" alt="Screen Shot 2022-10-10 at 14 44 09" src="https://user-images.githubusercontent.com/12952590/194924650-49076883-a7ff-4dd2-904f-3344fbbef9ae.png">

```rust
rustup --version
rustup 1.25.1 (bb60b1e89 2022-07-12)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.64.0 (a55dd71d5 2022-09-19)`
```

#### What are the steps to reproduce the behavior?

```python
import connectorx as cx

postgres_url="postgresql://user:pwd@localhost:5432/database"
query = "select * from name_of_the_table"
cx.read_sql(postgres_url, query)
```

##### Database setup if the error only happens on specific data or data type

Happens in all tables.

##### Example query / code

```sql
select * from users;
```

#### What is the error?

```thread '<unnamed>' panicked at 'not implemented: citext', /Users/runner/work/connector-x/connector-x/connectorx/src/sources/postgres/typesystem.rs:100:22```

**Comment by wangxiaoying** [comment]
Hi @Sirsirious , can you try version `0.3.1-alpha.9` to see whether it works now?

**Comment by Sirsirious** [comment]
I can confirm that now I don't receive the same error and that I can have the expected results. Is there any scheduling for the stable release?

**Comment by wangxiaoying** [comment]
@Sirsirious Planning to have next stable release `0.3.1` by the end of this month.
