### ISSUE TITLE
Oracle -> panicked at 'not implemented: Type Long

### ISSUE THREAD

**Issue by wKollendorf** [sfu-db/connector-x#375]
**What language are you using?**
Python 🐍

**What version are you using?**
0.3.1a5

**What database are you using?**
Oralce

**What dataframe are you using?**
Polars

**Can you describe your bug?**
query = 'select id, XMLAgg(XMLElement(test, test)) group by id'
cx.read_sql(oracle_url, query, return_type='polars')

It only panickes when there is an column with XMLTYPE value.

**ERROR:**
thread '<unnamed>' panicked at 'not implemented: Type Long not implemented for oracle!', C:\Users\xxx\AppData\Local\Temp\pip-req-build-ilsiub31\connectorx\src\sources\oracle\typesystem.rs:54:18

**Comment by wangxiaoying** [comment]
Hi @wKollendorf , can you try version 0.3.1-alpha.9 to see whether it works now?

**Comment by wKollendorf** [comment]
Working perfectly fine now. Thanks!
