### ISSUE TITLE
ModuleNotFoundError: No module named 'connectorx.connectorx_python' in mac os with python 3.11

### ISSUE THREAD

**Issue by akjoshi009** [sfu-db/connector-x#410]
#### What language are you using?

Replace this text with the **Rust** or **Python**.

#### What version are you using?

Replace this text with the version.

#### What database are you using?

e.g. PostgreSQL, MySQL

#### What dataframe are you using?

e.g. Pandas, Arrow

#### Can you describe your bug?

Give a high level description of the bug.

#### What are the steps to reproduce the behavior?

If possible, please include a **minimal simple** example including:

##### Database setup if the error only happens on specific data or data type

Table schema and example data

##### Example query / code

```
your
code
goes
here
```

#### What is the error?

Show the error result here.

**Comment by Gerei** [comment]
I just updated python 3.11, which is the same error. And 3.9 is normal
Running environment win10, query the MySQL database. An error is reported when quoting. The error content is as follows: 

![image](https://user-images.githubusercontent.com/69304083/204214035-ac9bfd97-88a1-47c0-9cc8-caa526fee4c5.png)
`
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\IPython\core\interactiveshell.py", line 3433, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-6b2cbf67d707>", line 1, in <module>
    import connectorx
  File "C:\PyCharm\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\connectorx\__init__.py", line 3, in <module>
    from .connectorx_python import read_sql as _read_sql
  File "C:\PyCharm\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'connectorx.connectorx_python'
`

**Comment by lmancilla** [comment]
Downgrading to 3.10 solves this issue.

**Comment by tempbottle** [comment]
build from source code may solve this.
use maturin to build python3.11 wheel is just run:
`maturin build --release` in connector-x/connectorx-python dir will build out the wheel file.
and run `pip install target/path/to/wheel/file` will complete the installation.

**Comment by wangxiaoying** [comment]
The latest [version](https://pypi.org/project/connectorx/0.3.2a2/#files) has wheel files for python 3.11 now.
