### ISSUE TITLE
 No module named 'connectorx.connectorx_python'

### ISSUE THREAD

**Issue by avico78** [sfu-db/connector-x#434]
Running on Windows 11 Pro
Python 3.11

pip install connectorx  
completed successfully but not able to import:
```
  import connectorx as cx
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\connectorx\__init__.py", line 3, in <module>
    from .connectorx_python import read_sql as _read_sql
ModuleNotFoundError: No module named 'connectorx.connectorx_python'
```
Following search I saw suggestion using whl 
I tried connectorx-0.3.1-cp310-none-win_amd64.whl but got same result .

**Comment by kmatt** [comment]
`pip` installation on Python 3.10 works. Wheels for Python 3.11 don't appear to be available yet.

**Comment by wangxiaoying** [comment]
For 3.11 please check for the newest alpha version: https://pypi.org/project/connectorx/0.3.2a2/#files
