### ISSUE TITLE
Cannot connect to redshift

### ISSUE THREAD

**Issue by kar-man** [sfu-db/connector-x#456]
#### What language are you using?

Python

#### What version are you using?

3.9

#### What database are you using?

Redshift

#### What dataframe are you using?

Pandas
#### Can you describe your bug?

Cannot connect to redshift

#### What are the steps to reproduce the behavior?

#%%
import connectorx as cx

db = ""postgresql://username:password@server:port/database""
query = "SELECT * FROM order_details LIMIT 10"

try:
    result = cx.read_sql(db, query)
    print(result)
except Exception as e:
    print(f"Error: {e}")

##### Database setup if the error only happens on specific data or data type

Table schema and example data

##### Example query / code

```
your
code
goes
here
```

#### What is the error?

Error: db error: ERROR: syntax error at or near "("

**Comment by wangxiaoying** [comment]
Hi @kar-man , please replace `postgresql://` with `redshift://` in your url

**Comment by kar-man** [comment]
Thank you. It works
