### ISSUE TITLE
Support for PostgreSQL `name` type

### ISSUE THREAD

**Issue by nhurden** [sfu-db/connector-x#501]
#### Describe your feature request

Currently querying the `usename` column on `pg_user` (`select usename from pg_user`) fails with:
```
thread '<unnamed>' panicked at 'not implemented: name', /Users/runner/work/connector-x/connector-x/connectorx/src/sources/postgres/typesystem.rs:100:22
```

https://github.com/sfu-db/connector-x/blob/main/connectorx/src/sources/postgres/typesystem.rs#L101

That column is using the postgres `name` type:  
- https://www.postgresql.org/docs/current/datatype-character.html#DATATYPE-CHARACTER-SPECIAL-TABLE
- https://dba.stackexchange.com/questions/217533/what-is-the-data-type-name-in-postgresql

**Comment by Jordan-M-Young** [comment]
Hi @nhurden I've fixed [similar issues](https://github.com/sfu-db/connector-x/issues/480) and will try to take a stab at yours over the weekend. Cheers

**Comment by Jordan-M-Young** [comment]
@nhurden I've opened a PR here https://github.com/sfu-db/connector-x/pull/504. Feel free to checkout the feature branch and test it yourself while the PR is reviewed.

**Comment by Jordan-M-Young** [comment]
@nhurden The PR has been merged, you should be able to use name types relatively soon

**Comment by nhurden** [comment]
Can confirm this is now working in 0.3.2. 👍
