### ISSUE TITLE
Start building wheels for python 3.12

### ISSUE THREAD

**Issue by hagsted** [sfu-db/connector-x#527]
Python 3.12 is on the horizon, and the first rc build is available. Is it not time to consider building for this python version? For instance the next alpha 8 would be nice to also have for python 3.12, so we can start to test all our code against the new version of python.

**Comment by Exmilien** [comment]
Hello, do we have a target date for Python 3.12 support in a new release ?

**Comment by WolfEYc** [comment]
bump

**Comment by fdcastel** [comment]
> Hello, do we have a target date for Python 3.12 support in a new release ?

Yes. Dec' 2042.

**Comment by wesleykendall** [comment]
Bump, it would be nice to at least know if there's an easy way to build wheels on our own so that we don't have to wait for a release to PyPI

**Comment by aleewen** [comment]
It would be nice to have support for Python 3.12 especially when Polars is now supporting it but requires the latest version of connectorx as an optional dependency.

**Comment by owenlamont** [comment]
I too really want this, connector-x is the only package I use that still doesn't support 3.12

**Comment by mkleinbort-ic** [comment]
All good here? It's a blocker to moving to 3.12

**Comment by alexander-beedie** [comment]
Any chance of a build for Python 3.12? It's turning into a hard blocker for a lot of folks; I can see it's a lot of work to maintain the project, and there haven't been many merges in recent months, but this one would be a _really_ useful one to get out. Many thanks!🤞

**Comment by dovahcrow** [comment]
I put some initial effort under the branch https://github.com/sfu-db/connector-x/tree/3.12. There are still dependency issues and CI issues tho.

**Comment by WolfEYc** [comment]
> I put some initial effort under the branch https://github.com/sfu-db/connector-x/tree/3.12. There are still dependency issues and CI issues tho.

Python amiright

**Comment by Data-Jack** [comment]
Adding to the demand for this as well.
Getting this error when trying to install specific version from python:3.12 docker image.

`ERROR: Could not find a version that satisfies the requirement connectorx==0.3.2 (from versions: 0.2.3)`

**Comment by hagsted** [comment]
I am tempted to say that it would be nice if python 3.13 support was also prepared, as the first beta has been released.

**Comment by h0rn3t** [comment]
bump

**Comment by wangxiaoying** [comment]
0.3.3 has been published to pypi with python 3.12 support. Please feel free to check out.
