### ISSUE TITLE
Often appear  Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by hakulat2023** [sfu-db/connector-x#534]
#### What language are you using?

Python

#### What version are you using?

0.3.2

#### What database are you using?

MySQL

#### What dataframe are you using?

Pandas

#### Can you describe your bug?

Segmentation fault (core dumped)

#### What are the steps to reproduce the behavior?

just connectorx.read_sql

##### Database setup if the error only happens on specific data or data type

Table schema:
CREATE TABLE `tbl` (
  `a` int(11) NOT NULL,
  `b` int(11) NOT NULLunsigned NOT NULL,
  `c` int(11) NOT NULL DEFAULT '1',
  `d` int(11) DEFAULT '1',
  `e` tinyint(4) NOT NULL DEFAULT '0',
  `f` int(11) NOT NULL DEFAULT '0',
  `g` tinyint(4) NOT NULL DEFAULT '0',
  `h` text CHARACTER SET utf8,
  `i` datetime DEFAULT NULL,
  `s` tinyint(4) DEFAULT '0',
  PRIMARY KEY (`a`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=COMPACT;

##### Example query / code

```
import connectorx as cx

def cx_read_sql(addr, sql):
    cx_addr = cx_format_mysql_addr(addr)
    log_addr = cx_addr.split('@')[1]
    print(f'cx.read_sql: {sql} from {log_addr}')
    return cx.read_sql(cx_addr, sql)

df = cx_read_sql(addr, sql)
```

#### What is the error?
Often appear, somttimes success

```
[2023-08-29T09:47:26Z DEBUG connectorx::pandas] Protocol: binary
[2023-08-29T09:47:26Z DEBUG connectorx::dispatcher] Run dispatcher
[2023-08-29T09:47:26Z DEBUG connectorx::dispatcher] Prepare
[2023-08-29T09:47:26Z DEBUG connectorx::dispatcher] Fetching metadata
[2023-08-29T09:47:26Z DEBUG connectorx::dispatcher] Try get row rounts for entire result
[2023-08-29T09:47:26Z DEBUG connectorx::dispatcher] Manually count rows of each partitioned query and sum up
[2023-08-29T09:47:26Z DEBUG connectorx::sql] Transformed count query: SELECT count(*) FROM (SELECT a, b, c, d, e, f, g, h, if(i IS NULL, 0, unix_timestamp(i)) AS j FROM tbl WHERE s = 1) AS CXTMPTAB_COUNT
[2023-08-29T09:47:51Z DEBUG connectorx::dispatcher] Allocate destination memory: 3504489x9
[2023-08-29T09:47:51Z DEBUG connectorx::dispatcher] Create destination partition
[2023-08-29T09:47:51Z DEBUG connectorx::dispatcher] Start writing
[2023-08-29T09:48:11Z DEBUG connectorx::dispatcher] Finalize partition 0
Segmentation fault (core dumped)
```

**Comment by wangxiaoying** [comment]
Hi @hakulat2023 , thanks for the report. May I ask does this core dump also appear in earlier releases/meta release or does it only happen in 0.3.2? It will help to narrow down the cause.

**Comment by hakulat2023** [comment]
> 

0.3.1 also happens, other earlier releases not tested

**Comment by wangxiaoying** [comment]
Is this table constantly updating? If it is, I suspect the reason is due to the different query result size between the `COUNT`  query in the log and the actual result we fetched from db by issuing the real query.

**Comment by hakulat2023** [comment]
> Is this table constantly updating? If it is, I suspect the reason is due to the different query result size between the `COUNT` query in the log and the actual result we fetched from db by issuing the real query.

I guess so
could we reserve a certain percentage of rows by setting to work around this problem

**Comment by wangxiaoying** [comment]
> > Is this table constantly updating? If it is, I suspect the reason is due to the different query result size between the `COUNT` query in the log and the actual result we fetched from db by issuing the real query.
> 
> I guess so could we reserve a certain percentage of rows by setting to work around this problem

Pandas requires to have a continuous block. One way to work around this problem is to set the destination to `arrow` instead of `pandas`, and then convert arrow dataframe to pandas dataframe. Something like this:

```python
import connectorx as cx

table = cx.read_sql(conn, query, return_type="arrow2")
df = table.to_pandas(split_blocks=False, date_as_object=False)
```
