### ISSUE TITLE
Bump pyo3 version for connectorx-python

### ISSUE THREAD

**Issue by 0xbe7a** [sfu-db/connector-x#537]
I am trying to build connector-x for osx arm64 and python 3.10 for conda-forge. This is currently failing due to a bug in pyo3 0.14, which connectorx-python is currently using. This issue would be resolved by bumping pyo3 to 0.15.

https://github.com/conda-forge/connectorx-feedstock/pull/15#issuecomment-1709665741

**Comment by wangxiaoying** [comment]
Hi @0xbe7a , thanks so much for working on conda-forge release! I just bumped `pyo3`'s version to 0.15 in this [commit](https://github.com/sfu-db/connector-x/commit/6370fd1d03ef15dc7b257005a57ef88c7ce059e1). Does it work?

**Comment by 0xbe7a** [comment]
Works great and the builds are working now. Could you still create a new release 0.3.3 as we are a bit reluctant to pin a commit?

**Comment by 0xbe7a** [comment]
Any tag works

**Comment by 0xbe7a** [comment]
I mean a git tag

**Comment by wangxiaoying** [comment]
IC. Does this work? https://github.com/sfu-db/connector-x/releases/tag/0.3.3a1

**Comment by 0xbe7a** [comment]
sorry, missed it. that works 👍
