### ISSUE TITLE
Release connectorx 0.3.2 on crates.io

### ISSUE THREAD

**Issue by lukapeschke** [sfu-db/connector-x#538]
#### What language are you using?

**Rust**

#### What version are you using?

0.3.1, but I'd like to use 0.3.2 in order to be able to use polars 0.32.0. It seems to have been out for a week now.

Thanks a lot for your work on connector-x, really nice lib :slightly_smiling_face:

**Comment by lidh15** [comment]
also looking forward to this release

**Comment by wangxiaoying** [comment]
0.3.2 is released on crates.io: https://crates.io/crates/connectorx !

**Comment by lukapeschke** [comment]
Thanks a lot :pray:
