### ISSUE TITLE
rust connector-x 0.3.2 not working with polars 0.33

### ISSUE THREAD

**Issue by lidh15** [sfu-db/connector-x#543]
#### What language are you using?

**Rust**

#### What version are you using?

0.3.2

#### What database are you using?

MySQL

#### What dataframe are you using?

Arrow2, I mean Polars

#### Can you describe your bug?

you know if I use a polars version different from connector-x is using, the dataframes will have mismatched types (polars::prelude::DataFrame VS polars_core::frame::DataFrame).

#### What are the steps to reproduce the behavior?

well, simply use `polars = "0.33"` and `connectorx = { version = "0.3.2", features = ["src_mysql", "dst_arrow2"]} ` in Cargo.toml and try to `get_arrow2()` and call `polars()` to return a dataframe

#### What is the error?

mismatched types
expected `polars::prelude::DataFrame`, found `polars_core::frame::DataFrame`

**Comment by lidh15** [comment]
and it seems that polars 0.33 is bonded with arrow2 0.18 while polars 0.32 is with arrow2 0.17

**Comment by davidgovea** [comment]
Maybe a new destination is warranted? Seems like polars is using a custom fork of arrow2, so the destination code would look very similar to dst_arrow2

**Comment by lidh15** [comment]
the good news is that I modified my codes related to polars so that it could be locked to an older polars version which works with connect-x 0.3.2
