### ISSUE TITLE
Support SQL ending with a semicolon

### ISSUE THREAD

**Issue by theelderbeever** [sfu-db/connector-x#575]
#### Describe your feature request

Currently, you can't submit queries that terminate with a semicolon. It would be nice to be able to able to include these. Primary reasons being that it is part of the standard already and a lot of syntax highlighters trigger off of the `;` to stop highlighting.

<img width="1739" alt="image" src="https://github.com/sfu-db/connector-x/assets/29295582/a6bed233-73a0-4626-a93b-526255643cf0">

**Comment by Jordan-M-Young** [comment]
Hey @theelderbeever, 

I think this should simple as adding a few well placed query.replace(";","") statements [here](
https://github.com/sfu-db/connector-x/blob/main/connectorx-python/connectorx/__init__.py).

Happy to take a look at this when I have a chance.

**Comment by theelderbeever** [comment]
@Jordan-M-Young Awesome and greatly appreciated!

**Comment by aimtsou** [comment]
Good afternoon,

I have written some code which i think it fixes the problem, I am not sure though if we need to write some extra tests for that because the behavior for the tests should not change.

What do you think @theelderbeever

**Comment by theelderbeever** [comment]
@aimtsou do you have a branch or something that I can look at?

**Comment by aimtsou** [comment]
> @aimtsou do you have a branch or something that I can look at?

https://github.com/aimtsou/connector-x/blob/aimilios_semicolon/connectorx-python/connectorx/__init__.py
Lines 207-212

**Comment by Jordan-M-Young** [comment]
@theelderbeever Just merged this [PR](https://github.com/sfu-db/connector-x/pull/599) Hopefully things are good to go now
