### ISSUE TITLE
Please cut python 3.8 wheel for 0.3.3

### ISSUE THREAD

**Issue by rafmagns-skepa-dreag** [sfu-db/connector-x#629]
the python version was constrained in #533 to >=3.8 but no 3.8 wheel was published for 0.3.3. Please publish a 3.8 wheel. I also took a quick glance at the CI configs and see that you're still building against 3.7. It might be time to update that as well

**Comment by cdeil** [comment]
Close?

**Comment by rafmagns-skepa-dreag** [comment]
Yes
