### ISSUE TITLE
No 0.3.3 Python wheel for Linux on ARM

### ISSUE THREAD

**Issue by eden881** [sfu-db/connector-x#639]
#### What language are you using?

Python

#### What version are you using?

connectorx: 0.3.3
Python: 3.11

#### Can you describe your bug?

connectorx 0.3.3 does not provide an ARM Python wheel for Linux, only for macOS.

#### What are the steps to reproduce the behavior?

I'm using a Mac with M2 Pro. When I spin up a Docker container from a `python:3.11` image, I can't install the package for connectorx, presumably because Docker Desktop for Mac uses a Linux VM behind the scenes.
When not specifying a version, it defaults to install version 0.2.3 in the container.

However, when using a Python 3.11 venv directly on my machine, connectorx 0.3.3 installs without issues directly from the correct wheel.

#### What is the error?

```shell
root@46e47c8df442:/# pip install connectorx==0.3.3
ERROR: Could not find a version that satisfies the requirement connectorx==0.3.3 (from versions: 0.2.3)
ERROR: No matching distribution found for connectorx==0.3.3
```

**Comment by bfgdigital** [comment]
Exact same issue.
Can't be used in AWS CodeBuild projects, but works locally.

**Comment by wangxiaoying** [comment]
Redirect to #240
