### ISSUE TITLE
How to use self signed cert with trino connection

### ISSUE THREAD

**Issue by EnguerranDev** [sfu-db/connector-x#643]
Trino do not accept basic authentication using http.

Using https it requires tls/ssl cert, the trino-python library circumvent this by using verify=false.

Is there a way to pass the verify=false as a parameter in the connection string or any other way to connect as the current documentation propose trino+https with the username and password in the connection string; this couldn't work.

Thanks a lot guys!

**Comment by RosenV95** [comment]
Seconding for this, dealing with the same issue atm.

**Comment by nalindalxr** [comment]
Dealing with the same problem.

**Comment by tooptoop4** [comment]
@domnikl https://github.com/nooberfsh/prusto/issues/50
