### ISSUE TITLE
Python 3.13 support

### ISSUE THREAD

**Issue by hagsted** [sfu-db/connector-x#694]
Hi Connector-x team

I am a happy user of Connector-x, but like to more forward to new python version soon after they are released. Is it possible that you could update connector-x to support python 3.13 now that it has been released.

Best regards Kristian

**Comment by wangxiaoying** [comment]
We are waiting for all our dependencies like [numpy](https://github.com/PyO3/rust-numpy/pull/435) to release the newest version (0.22 on cargo in this case). Once they are done, we can release a new stable version that supports python 3.13.

**Comment by wangxiaoying** [comment]
Python 3.13 is now supported from version 0.4.0! Please feel free to have a try.

**Comment by carepollo** [comment]
> Python 3.13 is now supported from version 0.4.0! Please feel free to have a try.

Wrong: Getting error

`ERROR: Could not find a version that satisfies the requirement connectorx==0.3.2 (from versions: 0.2.3) `

When deploying in docker container

**Comment by EricFecteau** [comment]
Have you tried `connectorx==0.4`?

**Comment by carepollo** [comment]
> Have you tried `connectorx==0.4`?

Yes I have 

`ERROR: Could not find a version that satisfies the requirement connectorx==0.4.1 (from versions: 0.2.3) ERROR: No matching distribution found for connectorx==0.4.1`

**Comment by wangxiaoying** [comment]
Hi @carepollo , what is your local environment? You can find all our precompiled wheel files [here](https://pypi.org/project/connectorx/0.4.1/#files). If there is no matching one for you, you have to build connectorx like [this example](https://github.com/sfu-db/connector-x/issues/386#issuecomment-2455556217) for now.
