### ISSUE TITLE
Updating jr4s to v0.17.0 to remove CVE

### ISSUE THREAD

**Issue by zacqed** [sfu-db/connector-x#712]
Referring to the discussion here: https://github.com/astonbitecode/j4rs/issues/137#issuecomment-2503393580, one can see the CVE that is being pointed out for j4rs, this version is being currently used in connectorx. Please if you do a release with the version v0.17.0 as confirmed by the author.

Thanks.

**Comment by zacqed** [comment]
@wangxiaoying - Would you be able to have a look at this?

**Comment by wangxiaoying** [comment]
@zacqed  thanks for the PR. j4rs is upgraded (e732c0a445b84f2c81c4b164f4a12be38dede95f).
