### ISSUE TITLE
Add MySQL as source

### ISSUE THREAD

**Issue by wangxiaoying** [sfu-db/connector-x#73]

**Comment by doccosmos** [comment]
Does this mean that MySQL/MariaDB is not yet a viable source? I've tried connecting using the connection string that I normally post to pd.read_sql_query and I'm getting "invalid connection string"

**Comment by dovahcrow** [comment]
@doccosmos unfortunately yes. We currently only support Postgres. But don't be disappointed, MySQL support is currently being worked on!

**Comment by doccosmos** [comment]
I wish the article that described connectorX or the front page of connectorX said that.

— M.

**Comment by dovahcrow** [comment]
Yeah, we mentioned it here https://github.com/sfu-db/connector-x#parameters. But I think we should make it more explicitly in the article and in the README.

**Comment by mrtztg** [comment]
WTF.
I was so excited about this library. But I realized that MySQL is not supported yet.
Please add this as soon as possible.
We are waiting for that.

**Comment by dovahcrow** [comment]
> WTF.
> I was so excited about this library. But I realized that MySQL is not supported yet.
> Please add this as soon as possible.
> We are waiting for that.

Sorry for not being clear in the blog post. We currently have made MySQL the first priority and are working on that.

**Comment by mrtztg** [comment]
> > WTF.
> > I was so excited about this library. But I realized that MySQL is not supported yet.
> > Please add this as soon as possible.
> > We are waiting for that.
> 
> Sorry for not being clear in the blog post. We currently have made MySQL the first priority and are working on that.

Thanks. When the new version will be released?

**Comment by dovahcrow** [comment]
Hi @mrtztg and @doccosmos  we are pleased to inform you that we just released the connectorx `0.2.0a2` version, which includes MySQL and SQLite support. You can try it using `pip install -U connectorx==0.2.0a2`.

A simple benchmark on the TPC-H lineitem table (9G) shows we are 36x faster than pandas.

![tpch-mysql](https://user-images.githubusercontent.com/998606/125568464-ad83401b-b693-4f62-a7cf-55d94b6872ba.gif)

**Comment by mrtztg** [comment]
Thanks @dovahcrow ❤️❤️❤️. I'm going to try it.

**Comment by dovahcrow** [comment]
I'm gonna close this issue now. If you find any bugs or request more features related to MySQL, please just open another issue.
