### ISSUE TITLE
RuntimeError: TypeError: Argument 'placement' has incorrect type

### ISSUE THREAD

**Issue by jmitterh** [sfu-db/connector-x#93]
File "D:\BOT\PostgreSQLConnection\venv\lib\site-packages\connectorx\__init__.py", line 98, in read_sql
    partition_query=partition_query,
RuntimeError: TypeError: Argument 'placement' has incorrect type (expected pandas._libs.internals.BlockPlacement, got list)
OR
  File "D:\BOT\PostgreSQLConnection\venv\lib\site-packages\connectorx\__init__.py", line 98, in read_sql
    partition_query=partition_query,
RuntimeError: TypeError: Argument 'placement' has incorrect type (expected pandas._libs.internals.BlockPlacement, got int)

**Comment by dovahcrow** [comment]
Thanks for the bug report! Pandas recently changes the internal block structure in their 1.3.0 release. 
@jmitterh Can you have a try on downgrading pandas to 1.2 to see if it works?

**Comment by jmitterh** [comment]
Thank you for prompt reply. Yes, downgrading to pandas 1.2.0 solved the issue I was having.
